### ISSUE TITLE
Docker compose issue

### ISSUE THREAD

**Issue by anistark** [knadh/listmonk#10]
Tried setting up the project via docker.
Cloned, edited the `config.toml` file. And Updated data there.
Then ran the below and please find the response as well below.

```
➜ docker-compose up -d
Starting listmonk_db_1 ...
listmonk_demo-db_1 is up-to-date
Starting listmonk_db_1 ... error

ERROR: for listmonk_db_1  Cannot start service db: driver failed programming external connectivity on endpoint listmonk_db_1 (d1928b4afe6a4cfea6e6ac4e121ce983b95b29eb8b7473bb814fb09a469a09af): Bind for 0.0.0.0:9432 failed: port is already allocated

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint listmonk_db_1 (d1928b4afe6a4cfea6e6ac4e121ce983b95b29eb8b7473bb814fb09a469a09af): Bind for 0.0.0.0:9432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

docker app is using `9432` by default.

How do I resolve this?

**Comment by mr-karan** [comment]
@anistark Thanks for reporting this!

`docker-compose up -d` actually starts all services mentioned in the `docker-compose.yml` file, and we have `demo-db` and `db` both listed there. So erroneously _both_ the postgres containers are being launched together and that's why you see error: `failed: port is already allocated` for the second container. 

- Quick fix for this is `docker-compose up -d app db` which will not start the demo services.

- Alternatively, you can also remove the demo services from your `docker-compose` file and use the `docker-compose up -d` command. :smile: 

I'll send a PR shortly for this to update the instructions in README.

**Comment by anistark** [comment]
Ah, I see. I thought the `demo-db` is part of the process. Maybe initialise that on a separate port would do.

Just running `docker-compose up -d app db` works.

Btw, Great job with this project. Love the design. Kudos to both @knadh and @mr-karan :) 

But, while testing most of my emails are going to spam folder. Any pointers to that?

**Comment by knadh** [comment]
Thanks! Mail going to spam, that would depend on the reputation of your SMTP endpoint and the content of the mail.
