### ISSUE TITLE
Question: add attributes to forms

### ISSUE THREAD

**Issue by ebartz** [knadh/listmonk#105]
Hi there,

I have seen the feature that you can generate forms which let users subscribe to lists.

I cant seem to find how I would integrate user attributes as fields in those forms. Is that even possible?

It would be awesome if I cloud specify predefined attributes for a list which then get used in the forms generator. Or if the a field named "attributes.city" would result in a user attribute.

**Comment by knadh** [comment]
Attributes are stored as arbitrary JSON right now. Specifying a schema and allowing public input is complex as the schema would then need validations to sanitise external input (type, length etc.). Will end up being a DSL.

However, instead of using the simple HTML form, you could just make your own form, have a simple server-side program that accepts attributes, sanitizes, and finally inserts them into listmonk using the [subscriber API](https://listmonk.app/docs/apis/subscribers/).
