### ISSUE TITLE
SMTP issues

### ISSUE THREAD

**Issue by sumitmamoria** [knadh/listmonk#1105]
**Version:**
 - listmonk: [eg: v2.3.0]
 - OS: [Debian 11]

**Description of the bug and steps to reproduce:**
I have a custom SMTP server (mailcow) in place. It works fine for sending/receiving emails from standard email clients. After setting it up with listmonk when I hit "test connection" it throws an error: "dial tcp x.x.x.x:587: i/o timeout". I am using port 587 with STARTTLS and "skip TLS verification" as true. I have tried all sorts of combinations with the parameters, always shows the same error.

**Comment by knadh** [comment]
Seems like a Firewall issue. Could be at the network level or could be something like SELinux.

**Comment by sumitmamoria** [comment]
> Seems like a Firewall issue. Could be at the network level or could be something like SELinux. Tried `telnet yourhost.net 587` from inside the listmonk environment?

Yes. the telnet command works from inside the listmonk environment. Firewall is switched off, as far as I know. How do I check SELinux issue ?

**Comment by knadh** [comment]
Not familiar with SELinux, but if it's installed, it can block apps from making outgoing connections unless they're explicitly allowed. You should be able to search and figure out.

**Comment by sumitmamoria** [comment]
> Not familiar with SELinux, but if it's installed, it can block apps from making outgoing connections unless they're explicitly allowed. You should be able to search and figure out.

I tried listmonk docker as well. same problem.

**Comment by knadh** [comment]
hm, I'm not sure then. It must be a firewall issue somewhere if the TCP connection isn't even been established.

**Comment by sumitmamoria** [comment]
> hm, I'm not sure then. It must be a firewall issue somewhere if the TCP connection isn't even been established.

ok. let me investigate further

**Comment by vasilevich** [comment]
I think mailcow has a common issue of just doing what it does, extremely slowly, it happens to me too in other apps, maybe there is a way to increase the timeout in listmonk?

**Comment by sumitmamoria** [comment]
> I think mailcow has a common issue of just doing what it does, extremely slowly, it happens to me too in other apps, maybe there is a way to increase the timeout in listmonk?

Just curious...Did you try it with some other SMTP server where timeouts do not occur?

**Comment by vasilevich** [comment]
@sumitmamoria Unfortunately i didn't try listmonk yet, was just browsing through the issues, 
and felt that my input from personal experience with mailcow could be relevant.
from my experience, mailcow smtp on my server, can sometimes take up to 15 seconds to send. 
so I thought perhaps that is the issue since the error says "timeout" and he claimed that other email clients worked for him.
but then again, a firewall and a connection issue can also cause a timeout as well.

perhaps the op should try  a 3rd party smtp to test whether they will work, which might answer the firewall question.

or, as I said, maybe temporarily increase the timeout to just see whether that is the actual issue to like 20 seconds perhaps.
