### ISSUE TITLE
Directly confirm subscription when clicking "Confirm subscription" link in mail

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [knadh/listmonk#112]
Once a user enters it's mail address and received the mail to confirm the subscription it is a two step process:
1. Click the link in the mail
2. Click the "Confirm subscription(s)" button

Is there a way to skip the second step and have the user confirm it's subscription just by clicking the link in the mail? (I believe most newsletter I subscribed to handle it this way.)
Some users might be used to confirming a newsletter by simply clicking the link and don't pay enough attention that they have to take an extra step.

Edit: Same goes for the unsubscribe process.

**Comment by knadh** [comment]
This is by design to prevent users from clicking on the link accidentally and getting opted in without a chance to confirm.

That said, you can easily add something like `<script>document.getElementByID("#form").submit();</script>` to `public/templates/optin.html` and load this custom template using the `--static-dir` [option](https://github.com/knadh/listmonk/wiki/Configuration).

**Comment by atomtigerzoo** [comment]
Sorry to comment here, but would it be an option, to directly confirm the user as OP asked and show a confirmation page with a link to undo the confirmation (ie unsubscribe) if the user has clicked accidentally? Most people don't read, click the link in a mail and then close the window and aren't added to the list.

**Comment by knadh** [comment]
@atomtigerzoo you could customize the template to auto-confirm, as shown in the previous message, and show the unsubscription link along with the success message. Will explore this and see if this can be made the default behaviour.
