### ISSUE TITLE
Auto-confirm users

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#114]
My use case is to email users internally to our organization and will be importing them via csv file initially. It appears the behavior is that when a user is added and then sent a campaign they are asked to verify their account. Since I'm sending emails internally is there a way to verify automatically via an attribute or another way. 800+ people will be confused if I start using it with the need to confirm email addresses.

**Comment by cb3inco** [comment]
It appears that a double-optin list does send a email, but I added a user to a private single and it still sent an email.

**Comment by knadh** [comment]
- listmonk automatically sends an opt-in mail when you add a single subscriber from the UI.
- When you bulk import, it does not. For this, you can use the `Send opt-in campaign` option on the lists page.

- Single opt-in mail sending confirmation was a bug reported earlier this week. This has been fixed in the new release [v0.6.2-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.2-alpha).
