### ISSUE TITLE
"Message push timed out". Nothing send, after this message.

### ISSUE THREAD

**Issue by saginsa** [knadh/listmonk#1186]
We have big database - near 5 mln subscribers.
And we often use Tx messages in our system.

Some days ago, I am enabled some count Tx campaign in our system. Near 10000 mail/day.
And now i see regulary down of ListMonk.

I set in performance:
 - 10 - workers
 - 3 - currency 

In log we can see multiple message about our Tx:

_2023/02/12 09:03:26error sending message (0232 - код для входа в личный кабинет): message push timed out
2023/02/12 09:03:26message push timed out_

This is being treated by restart ListMonk services. (We use Postal SMTP server, but not restarted him)

I think, that multiple api Tx requests kill ListMonk workers.

Help for us please.

**Comment by knadh** [comment]
This is curious. I've never seen the workers getting blocked. We have an instance where we're able to broadcast ~40k messages / minute across 12mn subscribers. This happens when the items in the queue are taking too long to be pushed to the external  messenger, filling the queue.

- How many messages are you pushing to listmonk per second?
- Do you see any send timeout errors?
- What is the timeout you've configured on your SMTP server?
- What is the throughput of messages per second you're achieving at the SMTP (roughly)?
- What is the max connection value set on your SMTP server?

That said, assuming that you're pushing a lot of messages, worker count=3 is really low. Since these are IO bound workers, it should be several dozen at least, based on the available CPU count.

**Comment by saginsa** [comment]
Thank you. I will look for a solution and a problem, and I will write it here if I find.

**Comment by saginsa** [comment]
I paid attention, that usualy at first i see one time message

<subject> "354 Go ahead"

Now we set speed 10*10 and SMTP connections: 1000 
(but i dont search how many max coonections we can set on Postal. How I understood them unrestricted)

If we assume that smtp sessions fall off, then I do not understand why ListMonk does not initiate a new session in my case.

![image](https://user-images.githubusercontent.com/85064689/219048710-7591d86c-41dd-42ce-a5b6-3efc12520784.png)

According to the indicators of the virtual machine, ListMonk breathes and does not strain.
But in the end, everything is solved precisely by the ribbed ListMonk
