### ISSUE TITLE
Hello, I wanted to ask for help!

### ISSUE THREAD

**Issue by eujoseant** [knadh/listmonk#1291]
I don't understand much of it, but I deployed Listmonk on Railway. Now I want to upload a media, but every time I get **Error uploading file: open uploads/image.png: no such file or directory**.

How do I fix this? Or rather, how do I create a directory on Railway?

https://ibb.co/jHYWMns

**Comment by les-les** [comment]
in your listmonk directory (on your server that is runnin listmonk) 
you have to add a folder named _uploads_ (or whatever name you edited in the web gui)
after that upload of media files works 

br LES

**Comment by candidexmedia** [comment]
Uploading media via the filesystem doesn't work on Railway ([see this Twitter thread](https://twitter.com/candidexmedia/status/1623059650764501002)).

You have two choices:

1. Simplest: use a storage service like Cloudinary and copy the URL to the media. You get 25 GB of free uploads.
2. A bit more complex: In the settings, select `s3` instead of `filesystem`. Set up Amazon S3 account (or compatible services like Backblaze) and add the credentials.

![image](https://user-images.githubusercontent.com/95003834/232394139-1458d690-c450-4675-8680-62a8233ca620.png)
