### ISSUE TITLE
Mail rejected due to https://listmonk.app link in footer

### ISSUE THREAD

**Issue by okilele90** [knadh/listmonk#1351]
Mail from Listmonk v2.4.0 are rejected when sending to these french mail providers :

* free.fr
* laposte.net
* orange.fr
* wanadoo.fr

And probably a lot more.

I've tried to use multiple SMTP servers with no changes.
The solution I've found is to remove the following line from the Campaign's Templates footer since the issue seem to be  the `https://listmonk.app` link.

```
        <p>Powered by <a href="https://listmonk.app" target="_blank" style="color: #888;">listmonk</a></p>
```

This works but there remains a problem for double opt-in confirmation mails since this template that cannot easily changed from the UI.

**Comment by knadh** [comment]
Thanks for reporting. That is unfortunate. While it's not possible to change the system templates from the UI, it's still possible to load it from the disk.

**Comment by Satishglk** [comment]
Please can you help? How can that footer link be removed?

**Comment by MaximilianKohler** [comment]
@Satishglk did you experience the same issue?

OP mentioned how to remove it from `the Campaign's Templates footer`. 

For `for double opt-in confirmation mails`/system templates, you have to fetch the static files with `mkdir -p /etc/listmonk/static ; wget -O - https://github.com/knadh/listmonk/archive/master.tar.gz | tar xz -C /etc/listmonk/static --strip=2 "listmonk-mast`, then edit them to remove that link or maybe just make it plain text instead of an active link?.

**Comment by Satishglk** [comment]
My sincere apologies. I am using windows version and not familiar with Ubuntu (i tried installing ubuntu but ran into many issues not related to this app).  I am not sure how the above instructions to fetch static files translate to windows OS. I downloaded the code and was able to run listmonk. Want to make above changes. Any help will be greatly appreciated.  This is super cool app.

**Comment by MaximilianKohler** [comment]
For windows, I'm not sure. You might have to download the whole thing https://github.com/knadh/listmonk/archive/master.tar.gz and then extract the `static` directory. 

https://listmonk.app/docs/templating/#system-templates
