### ISSUE TITLE
Export subscribers as CSV

### ISSUE THREAD

**Issue by heyakyra** [knadh/listmonk#143]
This would be useful since CSV files can be imported. Would also be nice to be able to have custom attributes optionally exported as separate columns instead of one large JSON column

**Comment by knadh** [comment]
CSV export, agreed.

**Comment by cb3inco** [comment]
Would love this just for backup purposes. +1

**Comment by monarch0111** [comment]
@knadh Is there any deadline on this enhancement? I'm new to Go, would love to work on this.

**Comment by knadh** [comment]
> Is there any deadline on this enhancement?

Nope.

**Comment by monarch0111** [comment]
> > Is there any deadline on this enhancement?
> 
> Nope.

Can you please assign this to me?

**Comment by monarch0111** [comment]
Hello @knadh, I have a few questions to understand the requirement better and will design solution accordingly.

- Where should export as CSV option be available? In my opinion, I feel right place will be add an option is at `/subscribers` where users can export scoped subscribers based on filters / query.
- As of now, I see JSON export reponds back with all available attributes for a subscriber. Should we CSV format on similar lines as well? or users should be able to select attributes to be exported?
- Since export list can be big, it will be difficult to hold on to the connection and respond back with CSV file. Ideal behaviour in my experience has been to store CSV temporatily at any cloud storage (e.g. S3) and allow users to download when the file is available. My question here is since listmonk doesn't have a cloud storage functionality, will it be a good idea to store CSV on server disk?

Would like to know your thoughts.

**Comment by heyakyra** [comment]
> JSON export reponds back with all available attributes for a subscriber.
Should we CSV format on similar lines as well? or users should be able to
select attributes to be exported?

I would say just put attributes in their own columns which start with
"ATTRIBUTE: " and then the name of the attribute

**Comment by knadh** [comment]
@heyakyra I think the exported CSV should be exactly the same as the import format. The issue with flattening attributes in CSV is the loss of types (int, string, bool, arrays etc.) and nesting.

**Comment by knadh** [comment]
Done in https://github.com/knadh/listmonk/commit/ec1c4f30ed9fac85adcf7c6d0d8b14d802253fa0. This will be available in the next release.

![image](https://user-images.githubusercontent.com/547147/105578741-506ad680-5da8-11eb-989b-c12a8e05c034.png)
