### ISSUE TITLE
Multi-user feature question

### ISSUE THREAD

**Issue by mehulmpt** [knadh/listmonk#1448]
Hi @knadh 
We use listmonk at our organization, thank you for building it! This is not a bug report - only a question. I assume that listmonk also powers emails at zerodha which potentially has millions of emails in database. Without multi-user permission model, how do you guys make it work inside your org? Is the person responsible for operating listmonk only you/top management with full email access? If not, then how do you secure your listmonk installation from giving away all the emails to the one person operating it.

Just wanted to know any best practice we missed out.

**Comment by knadh** [comment]
> Is the person responsible for operating listmonk only you/top management with full email access?

Since we deal with customer data and are heavily regulated, we have a comprehensive risk framework on who gets to access what (with legal liabilities attached). Not just for listmonk, but all other interfaces that have data. The same framework applies to listmonk. Very few people (typically a single digit number) who have been specifically cleared under this framework to handle a certain interface get access.
