### ISSUE TITLE
Parentheses are not escaped properly in SQL query when searching for lists

### ISSUE THREAD

**Issue by tosie** [knadh/listmonk#1471]
**Version:**
 - listmonk: v2.5.1
 - OS: Debian 6.1.27-1 (2023-05-08) x86_64

**Description of the bug and steps to reproduce:**
When searching for a list with a string that contains parentheses, an error is returned by "pq".

Searching for `"My list (something)"` shows this error message:

```
error fetching lists: pq: syntax error in tsquery: "%My&list&(something)%"
```

Escaping the parentheses manually (`"My list \(something\)"`) works (see second screenshot).

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/20296/a0b05e37-b04e-4fec-ba48-95a324766926)

![image](https://github.com/knadh/listmonk/assets/20296/2a2a6490-66ca-48bb-a040-17f9e2ebfc38)

**Comment by FournyP** [comment]
Hi, I try to fetch lists with the API using this query : `'alerts' = ANY(lists.tags)`
So I got a query like this : `http://localhost:9000/api/lists?query=%27alerts%27%3DANY%28lists.tags%29`

But it doesn't work because of this issue. I've added `\` as you said to fix the problem and I get a 200 response but with empty data

The query is : `http://localhost:9000/api/lists?query=%27alerts%27%3DANY%5C%28lists.tags%5C%29` and as you can see, I don't get the same result between the API and the database
![image](https://github.com/knadh/listmonk/assets/64586968/b64b26cf-a70f-4c99-99fe-1ec6c1c39cbf)
![image](https://github.com/knadh/listmonk/assets/64586968/cb7fca14-b51d-488e-a6d9-f4ea9f5519ae)

Do you know why the API don't return the value ? 

Have a good day
