### ISSUE TITLE
Support for Google Cloud Storage media backend

### ISSUE THREAD

**Issue by paddycarver** [knadh/listmonk#1505]
**Is your feature request related to a problem? Please describe.**

I use Google Cloud to host my infrastructure, and would like to keep all my infrastructure within that cloud wherever possible. I don't want to use the `file` media backend because I treat servers as temporary cattle, and they often get rotated out by an autoscaler, etc. I could use the `s3` backend by using the Google Cloud Storage [S3 compatibility mode](https://cloud.google.com/storage/docs/interoperability) but I'd prefer to use the first-class support available for it, rather than a compatibility mode.

**Describe the solution you'd like**

The media backends look like a rather small amount of code, with a straightforward interface. I'd propose the following 3 solutions for consideration:

1. I'm happy to write and contribute a GCS backend using the existing setup. The big drawback here is you'd need to review the code, and code has a maintenance burden, so I won't pretend it's free to add just because I'm contributing it.
2. You could use the [`plugin`](https://pkg.go.dev/plugin) package to allow media backends to be developed as plugins outside your codebase. The big drawback is this only works on Linux, FreeBSD, and macOS, and there are some finicky versioning problems you get into like this. Something like [`go-plugin`](https://github.com/hashicorp/go-plugin) gets around this, but it's operationally a bit more complex and has some gotchas when running it.
3. You could allow users to provide their own URLs that media uploads get forwarded to, essentially developing a protocol for media uploads that ensures listmonk gets the information it needs to add to the database but that users can use whatever media hosting they care to. This is probably a lot of design work and will likely have a different kind of maintenance overhead, trying to get the design right.

Are any of these 3 options things you're interested in, or is this just a `wontfix` situation?

**Comment by knadh** [comment]
1) This might entail pulling in Google SDKs, which is a massive dependency. To avoid this specific problem with AWS, listmonk uses [simples3](https://github.com/rhnvrm/simples3), a zero dependency S3 implementation. Because S3 APIs are now pretty much a standard (MinIO uses this), this should be sufficient for most blob storage systems.

2) Go plugins are almost whole infeasible for programs that are distributed widely and compiled against different environments. WASM/WASI might one day might fulfill the Go plugins void.

3) This will need a standard API spec, right? Might as well be the S3 standard, which is already supported!

> Google Cloud Storage [S3 compatibility mode](https://cloud.google.com/storage/docs/interoperability) but I'd prefer to use the first-class support available for it, rather than a compatibility mode.

This is a first-class support for the S3 API spec as one of the interfaces amongst Google's on API, not necessarily a compatibility mode (which implies some sort of loss of degradation). It's absolutely fine to use this.

**Comment by paddycarver** [comment]
Asked and answered, thanks!
