### ISSUE TITLE
Unable to start the install_prod.sh script

### ISSUE THREAD

**Issue by Lau-po** [knadh/listmonk#1512]
**Version:**
 - listmonk: v2.5.1
 - OS: MacOS Ventura on M1 ship

**Description of the bug and steps to reproduce:**
When running the install_prod.sh script on macos after downloading every requirements, the script fails because it can't run the migration step.

We can see that the script locally creates 2 version of the configuration and docker compose files then, on the migration step, we get an error saying that listmonk can't reach the db (connection refused)

I changed the script to run both containers on the host network, It can now reach the db, but the password is not the right one (likely because of the duplication of the config). After putting the password to the default one It now can run the migration step and start, but the application is not reachable even if the container is alive and doesn't show any error.

**Screenshots:**
N/A

**Comment by Lau-po** [comment]
It seems to happen on Windows as well using docker desktop and git bash after updating the just as I did on macos.

**Comment by knadh** [comment]
@mr-karan @Thunderbottom would you know why this could be?

**Comment by Thunderbottom** [comment]
Seems like the compose file contains port mapping `9432:5432` as seen here in [`docker-compose.yml`](https://github.com/knadh/listmonk/blob/master/docker-compose.yml#L20), but the config ([here](https://github.com/knadh/listmonk/blob/master/config.toml.sample#L18), exactly) tries connecting to the default `5432`, which is untouched by the install-prod script.

@Lau-po, instead of running the container in host mode, could you try changing the port to `5432` in the docker compose file so it looks like `5432:5432` [here](https://github.com/knadh/listmonk/blob/master/docker-compose.yml#L20). Could you also run `docker compose down --remove-orphans -v` so that the existing data is all removed and then manually run `docker-compose up -d`  once without the script?
