### ISSUE TITLE
Name should be optional on import

### ISSUE THREAD

**Issue by russss** [knadh/listmonk#1630]
When importing contacts, the name field is required. This should be optional, as it is if you subscribe to a list though the signup form.

**Comment by MaximilianKohler** [comment]
This has been discussed before and marked "won't change".

**Comment by knadh** [comment]
Name can't be blank for reasons discussed in the past, https://github.com/knadh/listmonk/issues/967, https://github.com/knadh/listmonk/issues/594.

However, since this keeps coming up, perhaps there's a middlepath. If there's no name given, listmonk automatically extract the name part out of the e-mail and use it. Eg: `username@domain.com` -> `username`.

Any thoughts on this?

**Comment by russss** [comment]
Yeah, if you don't specify a name in the signup form or the API then the local part of the email address gets used, and I think it's quite likely that people will need to import a list of emails without names.

In fact the only reason the import fails here is because of this additional `if len(s.Name) == 0` check:

https://github.com/knadh/listmonk/blob/8f12c03a8a8ab7e44feb278685522e26f29b1ac2/internal/subimporter/importer.go#L640

I just edited this condition out and it imported my name-less CSV fine by setting the name to the local part of the email address.
