### ISSUE TITLE
v3.0.0 Campaign analytics missing data available in previous versions 

### ISSUE THREAD

**Issue by orthdron** [knadh/listmonk#1728]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu (Docker)

**Description of the bug and steps to reproduce:**
Campaign analytics missing percentage that was available in previous versions. Please close this ticket if this is intentional.

**Screenshots:**
Mouse hover
<img width="1227" alt="image" src="https://github.com/knadh/listmonk/assets/41769111/aa72728b-e0c3-4e92-b133-fd0aa5db74a1">

Entire page
![image](https://github.com/knadh/listmonk/assets/41769111/fbf4cef1-2e68-4efb-a099-a6f039ab829a)

**Comment by juggernut** [comment]
+ bump also is there any way to change the part where we show clicks / per link better visually , is quite hard to read it today :) .

**Comment by knadh** [comment]
Hi @Orthdron. Are you referring to the missing lines in the line graph? If yes, that's not normal. Please compare with the demo here: https://demo.listmonk.app/admin/campaigns/analytics?id=2&id=1

**Comment by MaximilianKohler** [comment]
@knadh I think they mean this:
![Screenshot 2024-03-10 063749](https://github.com/knadh/listmonk/assets/3606996/a4f6c002-b55c-4b27-a56b-860de5acb671)
![Screenshot 2024-03-10 063929](https://github.com/knadh/listmonk/assets/3606996/3f83e469-4812-4aeb-bda8-c138b9b47843)
![Screenshot 2024-03-10 063757](https://github.com/knadh/listmonk/assets/3606996/0328e0ab-121c-4c45-af32-b99359140f62)

**Comment by knadh** [comment]
Ah! This is indeed unintended. I missed recreating this when porting to the new chart lib. Will bring it back in the next version. Currently, the numbers only show on hover.

**Comment by knadh** [comment]
Turns out, chart.js doesn't support this out of the box. This plugin https://github.com/emn178/chartjs-plugin-labels/ adds labels, but I've been unable to make it work. Perhaps someone else can give it a shot.

**Comment by MaximilianKohler** [comment]
What about reverting back to the older version for now? It sounds you switched to something completely different?

**Comment by knadh** [comment]
The new chart lib is smaller and lighter (which is why it was switched in the first place). While the numbers not showing on the donut is a UX gap (it shows on hover), it's not a deal breaker. It can be achieved with some effort in the coming release.

**Comment by MaximilianKohler** [comment]
It only has the _view #_ on hover though. The old one had the percentage, which was much better since view # is already on the campaigns page so we don't need it again on the analytics page. Percentage is nowhere now. And the circle is always full instead of a percentage representation.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0

**Comment by Bowrna** [comment]
can I take a look at this issue if it persists? @knadh

**Comment by knadh** [comment]
Please do @Bowrna. Thank you!

**Comment by Bowrna** [comment]
I am stuck in this issue. 

Progress made until now:
Here in the given timestamp, there are 660 views(33%), out of the total 2000 sent mails. Previously, checking the code history, I can find that gauge value is set to max 100 and this percentage of data is filled in. But here I have written a tooltip callbackthat can compute percentage on hover. However, setting the max data is not working out for me. 
<img width="1154" alt="Screenshot 2024-09-30 at 3 02 36 PM" src="https://github.com/user-attachments/assets/a2bed339-2570-4c6c-a69a-953bc0d44da9">

To get the above graph, instead of filling the data with [660] , I have filled [660, 2000-660]. But this is not right, as its filling the remaining data part in donut and not setting the max value.(code line no. 232)
https://github.com/knadh/listmonk/blob/560789d506109f739bf89581956b4d18f120a719/frontend/src/views/CampaignAnalytics.vue#L231-L246

<img width="1154" alt="Screenshot 2024-09-30 at 3 02 48 PM" src="https://github.com/user-attachments/assets/99115cf8-6333-43ef-bac2-c40834bfdfd6">

I tried finding more about the chart plugin shared above from their demo  [here](https://emn178.github.io/chartjs-plugin-labels/samples/demo/). But I don't see any relevant example or code block, that will solve this particular issue.

Some other plugins like this seems to be useful.
https://github.com/greetclock/gauge-chart with demo here https://greetclock.github.io/gauge-chart/examples/samples/

https://github.com/haiiaaa/chartjs-gauge

This is where I am right now. Can anyone give me directions to bring a closure to this issue?

**Comment by knadh** [comment]
```javascript
        callbacks: {
          label: (item) => {
            const data = item.chart.data.datasets[item.datasetIndex];
            const total = data.data.reduce((acc, val) => acc + val, 0);
            const val = data.data[item.dataIndex];
            const percentage = ((val / total) * 100).toFixed(2);
            return `${item.label}: ${val} (${percentage}%)`;
          },
        },
```

Adding this to `options.tooltip{}` in `Chart.vue` seems to work.

![image](https://github.com/user-attachments/assets/a8874aa9-9dd2-4191-9ef3-a859ebbfe2ff)

**Comment by Bowrna** [comment]
@knadh I see, let me try this part and see how it works in case of a single campaign id.

**Comment by Bowrna** [comment]
@knadh I tried using the above snippet that you shared to view the analytics for one of the campaigns alone and this filled the entire donut graph like below. But it has to fill only the % part of the total sent mails right. Am I missing anything here? 

<img width="1318" alt="Screenshot 2024-10-08 at 12 38 19 PM" src="https://github.com/user-attachments/assets/aa8eb5c1-38da-4884-a8af-76de85b30f18">

**Comment by knadh** [comment]
> But it has to fill only the % part of the total sent mails right.

Ah no. It's simply showing the views registered on the selected campaign. If you select just one, 100% of the views will be that campaigns, whatever that number may be. If you pick two, it shows the breakdown indicating that X% of views was generated by one campaign and Y% of the views by the other.

**Comment by Bowrna** [comment]
> > But it has to fill only the % part of the total sent mails right.
> 
> Ah no. It's simply showing the views registered on the selected campaign. If you select just one, 100% of the views will be that campaigns, whatever that number may be. If you pick two, it shows the breakdown indicating that X% of views was generated by one campaign and Y% of the views by the other.

oops, I missed to verify this and assumed that way after seeing the old version screenshots. then the above snippet would work without a problem. let me try it and for longer campaign names, the hover would hide % details. let me test it locally and raise an updated PR.

**Comment by MaximilianKohler** [comment]
This is still broken for me on v6.1.0 (1b5e8d38 2026-03-29T13:18:16Z, linux/amd64). You can see that it shows 100% no matter what:

<img width="1026" height="654" alt="Image" src="https://github.com/user-attachments/assets/3e3da4e1-4a2d-4b82-83d8-bbf7a3ef505c" />

That is 531/2000.

EDIT:
Oh, I see what's wrong. It's not calculating it based on total sent, it's calculating it as a ratio between the selected campaigns. IE: if you select two campaigns, the percentages are between the two:

<img width="1049" height="706" alt="Image" src="https://github.com/user-attachments/assets/ed408dc9-1f05-48b8-a424-3e545328ca91" />
<img width="1017" height="669" alt="Image" src="https://github.com/user-attachments/assets/cdf3dfe0-fc97-4e1a-a061-cff6890e8989" />

Eg: 
581 is 35.49% of 1637 (1056 + 581)
1056 is 64.51% of 1637 (1056 + 581)

**Comment by MaximilianKohler** [comment]
I fed the info to ChatGPT and it gave me multiple replies & options. Let me know if I should submit one as a PR.

The full **first response** is: https://chatgpt.com/share/69fa87c9-b888-83e8-afcf-64c9db33ed7d

## Second response:

**1. Pass "sent count" into donut calculation**

Each campaign object `(camps[id])` already includes stats (including `sent`). We use that.

🔧 Update `makeCharts()` in `CampaignAnalytics.vue`

Replace this:

```
const points = campIDs.map((id) => {
  labels.push(camps[id].name);
  const cId = parseInt(id, 10);
  const sum = data.reduce((a, item) => (item.campaignId === cId ? a + item.count : a), 0);
  return sum;
});
```
With this:
```
const raw = campIDs.map((id) => {
  const cId = parseInt(id, 10);
  return data.reduce((a, item) => (item.campaignId === cId ? a + item.count : a), 0);
});

const points = campIDs.map((id, i) => {
  const sent = camps[id].sent || 0;
  const val = raw[i];

  labels.push(camps[id].name);

  // Avoid divide-by-zero
  return sent > 0 ? (val / sent) * 100 : 0;
});
```

**2. Fix tooltip (so it doesn’t recompute wrong %)**

Now that we’re passing percentages directly, the tooltip should NOT recompute using total.

Update `Chart.vue`. Find:
```
const total = data.data.reduce((acc, val) => acc + val, 0);
const percentage = ((val / total) * 100).toFixed(2);
return `${val} (${percentage}%)`;
```
Replace with:
```
return `${val.toFixed(2)}%`;
```
(Optional but better UX: include raw value too if you pass it later.)


## For making the percentages always show:

_Like they used to (instead of only on mouseover)_, it said to install/use `chartjs-plugin-datalabels` via:

```
import ChartDataLabels from 'chartjs-plugin-datalabels';
Chart.register(ChartDataLabels);
```
then in "donut options":
```
plugins: {
  datalabels: {
    color: '#333',
    formatter: (value) => `${value.toFixed(1)}%`,
  },
}
```
**OR** use
```
npm install chartjs-plugin-datalabels
```
Then update `Chart.vue`:
```
import Chart from 'chart.js/auto';
import ChartDataLabels from 'chartjs-plugin-datalabels';

Chart.register(ChartDataLabels);
```
Then add to donut options:
```
plugins: {
  datalabels: {
    color: '#333',
    formatter: (val) => `${val.toFixed(1)}%`,
    font: {
      weight: 'bold',
      size: 14,
    },
  },
  legend: {
    display: false,
  },
  tooltip: { ... }
}
```
**OR**
If you don’t want a new dependency, modify template in `CampaignAnalytics.vue`:
```
<div class="column is-2 donut-container">
  <chart type="donut" v-if="!v.loading" :data="v.donutData" />
  <ul v-if="v.donutData">
    <li v-for="(val, i) in v.donutData.datasets[0].data" :key="i">
      {{ v.donutData.labels[i] }} — {{ val.toFixed(2) }}%
    </li>
  </ul>
</div>
```
**OR**
In `Chart.vue`:
```
legend: {
  display: true,
}
```


## Description
This PR fixes an issue in the campaign analytics view where donut chart percentages are calculated incorrectly.

🐛 Bug
The donut chart currently calculates percentages based on the sum of selected campaigns' metrics:
`campaign_views / total_views_of_selected_campaigns`

This results in:
- Single campaign → always shows 100%
- Multiple campaigns → shows relative comparison instead of actual performance

✅ Fix
Percentages are now calculated per campaign:
`campaign_views / total_sent_for_campaign`

🔧 Changes
- Updated makeCharts() in CampaignAnalytics.vue to normalize values using campaign sent counts
- Updated tooltip logic in Chart.vue to display actual percentages instead of recalculating ratios
- Added persistent value display (via datalabels / inline labels)

📈 Result
- Accurate per-campaign engagement percentages
- No misleading comparisons across campaigns
- Improved UX: stats visible without hover
