### ISSUE TITLE
WYSIWYG Editor Converts Image URLs to Base64 Encoding on Edit

### ISSUE THREAD

**Issue by kSzajo** [knadh/listmonk#1777]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: ubuntu

Description
When editing an already uploaded image using the WYSIWYG editor, the src attribute of the <img> tag is changed from a direct URL (e.g., https://listmonk.local/uploads/) to a base64 encoded string. This behavior can significantly increase the size of the HTML content and potentially lead to performance issues, especially for emails or webpages with multiple images.

Steps to Reproduce
- Upload an image and edit using WYSIWYG editor (change brightness and rotate)
- Observe that the src attribute of the <img> tag has been changed from a URL to a base64 encoded string.
Expected Behavior: The src attribute of the <img> tag should retain the original URL format after editing the content in the WYSIWYG editor.

Actual Behavior: The src attribute of the <img> tag is converted to a base64 encoded string after content is edited in the WYSIWYG editor.
 
**Screenshots:**

<img width="686" alt="image" src="https://github.com/knadh/listmonk/assets/27929367/f86b08c5-89a7-46e5-a805-da4ca23c8f25">

**Comment by knadh** [comment]
Hi @kSzajo. This is unfortunately expected behaviour from the WYSIWYG editor. When you simply insert an image, it references the physical image on the server via the URL. When you edit it on the frontend, it no longer is the original image. The editor does not have the ability to then send the changed image to the backend, save it, and re-reference it with a new URL. I am afraid you will have to change the image outside of listmonk using an image editor and then upload the final version to listmonk and use it.

**Comment by kSzajo** [comment]
Can we then disable `imagetools`? https://github.com/knadh/listmonk/blob/master/frontend/src/components/Editor.vue#L250
