### ISSUE TITLE
bounce.go:170: error processing SES notification: notification type is not bounce

### ISSUE THREAD

**Issue by robguthrie** [knadh/listmonk#1807]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: [e.g. Ubuntu / Docker]

**Description of the bug and steps to reproduce:**
I've setup SNS notification topic as described in https://github.com/knadh/listmonk/issues/1668#issue-2080438101 but I'm not getting bounce notifications, in the logs I can see this error:
```
bounce.go:170: error processing SES notification: notification type is not bounce
```

I've tripple checked my settings and it seems correct.

**Comment by knadh** [comment]
SES sends many types of notifications. Perhaps you've enabled non-bounce notifications. I'm not familiar with SES config though.

**Comment by robguthrie** [comment]
Sorry, I should have added these are logs in response to me using the bounce@simulator.amazonses.com address to test. There are no other logs happening during this time, and the count of logs corresponds to my tests sent. 
The SNS topic confirmation request works correctly though.

Is there a way to enable more log output so I can see the body of the request?

**Comment by knadh** [comment]
There are no verbose payload logs. It should be fine to ignore those errors as non-bounce (bounce/complaint) notifications are discarded with that particular message. The simulator must be sending non bounce/complaint notifications.

**Comment by MaximilianKohler** [comment]
I wouldn't say this is fine and to ignore it. I haven't tested v3.0, but earlier versions had this issue before being fixed. I'm on v2.5.1 with that exact setup and everything works normally.

If you're only emailing bounce@simulator.amazonses.com, then there's clearly something wrong. The SES simulator does not send non-bounce/complaint notifications.

Since there are no verbose logs, you may want/have to try v2.5.1 to test, and if you're still getting the error then you've misconfigured something. If it works properly then it's a bug with v3.0.

Make sure that in this part of the instructions the 3rd option (1 bounce, 2 complaint, 3) is left blank:

> In the AWS console, go to [Simple Email Service](https://console.aws.amazon.com/ses/) and click "Verified identities" in the left sidebar.
> Click your verified domain and go to the "Notifications" tab.
> Next to "Feedback notifications", click "Edit".
> For "Bounce feedback" and "Complaint feedback", select the SNS topic you created earlier.

**Comment by MaximilianKohler** [comment]
>Is it safe to rollback from v3 to v2.5.1 without changing the database?

According to the docs it is not safe. I'd recommend cloning your server temporarily to test it.

**Comment by benstaf** [comment]
I have the same problem even with real bounce emails (not AWS SES bounce test emails)

I received the email bounce notification, but the bounce is not detected by Listmonk

**Comment by zkirill** [comment]
I followed the tutorial but was not receiving bounce notifications. The fix for me was after this line:

> 6. Click your verified domain and go to the "Notifications" tab.

I had to repeat this step for the "Email address" Identity Type as well in addition to "Domain" Identity Type.
