### ISSUE TITLE
Possibility to add attributes via `api/public/subscription`

### ISSUE THREAD

**Issue by spammads** [knadh/listmonk#1874]
I would like to pass the language my users subscribe to the public list api.
Therefore i use this endpoint to subscribe a user.
But the Api currently does not respect additional attributes passed.
It would be really nice if this would work 
```js
axios.post("https://newsletter.example.org/api/public/subscription", {
    email: emailFromFrontend,
    name: nameFromFrontend,
    list_uuids: ["abcdefghi-17fd-413c-8abf-aa5c65685929",""],
    attribs: { "language": languageFromFrontend }
})

**Comment by knadh** [comment]
Public API does not support attributes because it'll then allow the outside world to insert arbitrary data, which is opens up a big security hole.

If you'd like to insert attribs with subscription, you should use the private API behind a public endpoint you create that does the necessary data validation and sanitisation.
