### ISSUE TITLE
Using uploaded image as logo in email

### ISSUE THREAD

**Issue by PaulMcF1987** [knadh/listmonk#1921]
i feel as though I need to keep opening new threads, as rather than helping me find a solution to my problem you simply reply and then close the thread

I have managed to get the uploads section working as per my question [here](https://github.com/knadh/listmonk/issues/1888)

I am unsure how to use the images that I uplaod in my template...
I have tried using a path - <img src="uploads/image.png"> but that doesnt seem to work
Is there a variable code I should be using?
Do i need to use the full path, ie `/var/lib/docker/...../image.png?

**Comment by knadh** [comment]
The image (screenshot?) you have included in the issue is broken.

If you're using a Docker setup, Docker requires volumes to be mounted. For instance, on your server, the actual path may be `/home/yourusername/listmonk/files`, which can be mounted as `/listmonk/files` in the Docker compose file. This makes the directory on your host available to the Docker container and thus listmonk. In your settings, you'll then specify `/listmonk/files`. That's all I can recollect as my familiarity with Docker is limited.
