### ISSUE TITLE
Explore mechanisms for bounce processing

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#194]
Previous discussions: https://github.com/knadh/listmonk/issues/3 https://github.com/knadh/listmonk/issues/166

listmonk needs to be able to process bounced messages. The messages can be e-mails or arbitrary types (once the [postback](https://github.com/knadh/listmonk/tree/postback) branch goes live). When using a Postback messenger instead of the e-mail messenger for sending a campaign, messages are pushed to a an external HTTP endpoint in a standard format (see [discussion](https://github.com/knadh/listmonk/issues/146)), and the external server can relay it via any medium: SMS or FCM or anything. For these external message bounces to be processed, listmonk can expose a bounce API endpoint to which bounces can be posted. This approach doesn't work for e-mails and to process bounces, listmonk will have to connect to IMAP and POP servers, which is complicated.

The task is to figure out what's the best way to achieve bounce processing for e-mail and non-email postbacks. What is the state of the art or standard mechanisms?

**Comment by jackdanielux** [comment]
My non techie 0.02$:
When I was exploring list managers for my own use, I came across this feature:

1. Email Validator: So noobs like me (which is most of the crowd in digital marketing, blogging arenas) have no idea how to validate emails landing onto the subscribe page e.g. mailinator emails, yandex emails (temp emails to just receive the email which can get discarded if not used).  Due to a huge number of such emails most of the times, SES and other SMTP providers just blocklist your domain and you are left in the lurch looking for options.  Services are providing email validators that check the authenticity of emails (discard domains like mailinator etc. outright) and help reduce bounces (despite double opt-in)

**Comment by roshanjonah** [comment]
@knadh Any idea how we can proceed with this? We would love to integrate AWS so it makes our job so much easier.

Alternatively, what's the best way to mark a subscriber as blocklisted given they bounced via API? We can definitely integrate something quick in the meantime while we think this through.

**Comment by knadh** [comment]
@roshanjonah you can write a simple service that gets bounces from the AWS API (HTTP posts?) and
a) calls the update subscriber API to change their status
b) changes the user's status in the `subscribers` and/or `subscriber_lists` tables in the Postgres database directly.

**Comment by alerque** [comment]
Just for cross reference, have a look at [Lightmeter](https://lightmeter.io/)’s approach (code [on GitLab](https://gitlab.com/lightmeter)). In fact for anybody using Postfix for their SMTP delivery this might be a good pairing to use with Listmonk right now to manage bounces. It doesn't work for me since my MTA infrastructure is all running Exim, but it might be worth examining their approach. Instead of messing with the SMTP end directly or post-processing mails in POP/IMAP storage they are just monitory mail server log files to understand what happened to deliveries.

I don't necessarily suggest building such a mail log scanner into Listmonk itself, but it would be interesting if there was an API you could query to integrate data from Lightmeter or other projects like it to get delivery status from SMTP infrastructure similarly to how you might from Amazon's SES or other mail sending services.

**Comment by knadh** [comment]
The ideal approach would be to add built in support for reading bounce mails from a POP/IMAP box. This should cover the vast majority of small to medium size deployments. An additional API endpoint to which bounces can be piped should address all arbitrary external integrations.

**Comment by alerque** [comment]
I'm not sure reading POP/IMAP boxes would be the way to go actually. That involves lots of overhead to handle the login and message arrangements, plus the necessary parsing of actual bounces. I suggest it would be both lighter on the coding end plus more responsive in use to instead actually listen on an LMTP port as if you were a LDA and hence receive the bounce messages directly (and instantly).

**Comment by knadh** [comment]
While I do agree that it's indeed complex (which is why it's still pending despite being a fundamental requirement!), I don't think LMTP or any sort of piping will be something a significant percentage of the non-dev userbase will be able to setup. Running listmonk on Heroku or an EC2 instance and plugging in AWS SES is a common production pattern. I think it would be a worth the effort in terms of usability from a product perspective.

**Comment by knadh** [comment]
Bounce processing is now merged into master: https://github.com/knadh/listmonk/issues/166
