### ISSUE TITLE
SQL error when displaying subscribers list

### ISSUE THREAD

**Issue by thueske** [knadh/listmonk#1970]
**Version:**
 - listmonk: 3.0.0
 - OS: Alpine Linux with Docker

When I create a new list, whether private or public, I get an SQL error when I click on the number of members (for example: /admin/subscribers/lists/22) and no members are displayed, although I have previously subscribed to this list via the form. Older lists work without any problems.

The SQL error is:
`Error retrieving subscribers: sql: Scan error on column index 0, name "total": converting NULL to int is unsupported
`

**Comment by thueske** [comment]
It looks like the problem only exists when slow query caching is enabled.

**Comment by knadh** [comment]
Coincidentally, discovered and fixed this bug just a couple of days ago. https://github.com/knadh/listmonk/commit/fedc51514dafb818a333e70e17e54307be8a7cf3

It happens when there are lists with 0 subscribers. As a workaround for now, you can add at least one subscriber per list and then turn the query caching on.
