### ISSUE TITLE
how to create a trackable link

### ISSUE THREAD

**Issue by rezaa1** [knadh/listmonk#207]
I couldn't find a way in UI to create a trackable link, Can someone please explain how to generate it without going in database level.

**Comment by knadh** [comment]
This is document [here](https://listmonk.app/docs/templating/).

eg: `{{ TrackLink "https://yourlink.com" }}` to generate a tracked URL. If you're writing HTML, it'll be: `<a href="{{ TrackLink "https://yourlink.com" }}">The link</a>`

**Comment by jackdanielux** [comment]
Hi @knadh : I used the html version of the same, and sent out a test campaign - the link click was getting tracked but it kept giving an error of "message not found" and when I refreshed it 4-5 times (tried after 5 mins) it was working again.  Am I doing anything wrong or is this a know issue.  Basically I tried immediately of the mail landing in inbox, opened it and clicked on link - Not working for first 4-5 mins, then after 4-5 refreshes it starts working - link click however work immediately upon clicking.

**Comment by knadh** [comment]
hmm, that is very strange. Can you share the exact `{{ TrackLink }}` snippet you're using?

**Comment by cb3inco** [comment]
> hmm, that is very strange. Can you share the exact `{{ TrackLink }}` snippet you're using?

If I do this from the web interface and use the link option in the Rich Text editor like this:
![image](https://user-images.githubusercontent.com/14948644/97551797-00c57a80-1a06-11eb-9bc4-2e36c25fda6f.png)
I get the following error:
![image](https://user-images.githubusercontent.com/14948644/97551840-1044c380-1a06-11eb-8824-3aedd31db87e.png)
Am I doing something wrong? If I edit the Raw HTML directly then I need to get rid of:
![image](https://user-images.githubusercontent.com/14948644/97551980-42562580-1a06-11eb-9a07-91ee06a288bf.png)
And then modify the html correctly. If I switch back to Rich Text, I then have to switch back to Raw HTML and redo all my links.

If I need to create a different issue, I am happy to do that, I didn't want to hijack this one.

**Comment by knadh** [comment]
> If I do this from the web interface and use the link option in the Rich Text editor like this:

I suspect Quill editor is incorrectly escaping the quotes. Let me investigate this.

**Comment by jackdanielux** [comment]
@knadh : below is the error that I get:

![image](https://user-images.githubusercontent.com/71901268/97605727-fec6e000-1a34-11eb-9ab2-d0796400e4ed.png)

Here's the snapshot of the tracklink code that I use in my template:

Hi {{ .Subscriber.FirstName }}!

<p>Hope you are doing amazing and loved our last piece on <a href="{{ TrackLink "https://domain.com/example-post/" }}">Super Foods</a>.</p>

<p>In today's piece we learn more about everything related to Sandwiches. This is important and we just could not not cover it. <a href="{{ TrackLink "https://domain.com/category/sandwiches/" }}">Read more about it here</a>.</p>

All URL's are not opening.

**Comment by knadh** [comment]
The `not found` error happens when the URI is not recognised by listmonk. Since it starts working after multiple refreshes, I suspect there's something off with the Nginx routing.

Can you share the exact URL that is failing (you can remove the domain name. Just need to see the /xxx/xxx/xxx components).

**Comment by jackdanielux** [comment]
I also think this is due to NGINX routing.  Because listmonk UI in settings asks for the root of the software (and mentions that this needs to be without trailing slash, It was initially without trailing slash and without this, all URLs were being redirected to listmonk dashboard and asking for user ID and password, I followed proxy_pass method.  

Here's the URL that was converted by Tracklink : https://domain.com/link/0961661c-ab4e-40ea-8588-c1a58b97422b/98358833-2455-4c12-afda-137860460ece/1b832cee-fb32-4336-98eb-cd18bedb2ec5

**Comment by jackdanielux** [comment]
Here's my NGINX file contents (removed comments):
server {
       server_name domain.com;
             listen 443 ssl;
             listen [::]:443 ssl;
             ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # manage$
             ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # mana$
             include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
             ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_pass http://localhost:9000;
    }
}

server {
        listen 80;
        listen [::]:80;
        server_name domain.com;
        location / {
                proxy_pass http://localhost:9000;
                }
       return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS
        }

**Comment by jackdanielux** [comment]
I think I figured the problem:

All Opt-in URLs (irrespective of trailing slash being there in root URL or not) **are working fine** the format seems is https://domain.com/subscription/optin/1af18d7d-798e-42ef-87cd-d4b74494b19a?l=e16ceec4-8294-4cb2-a75f-07959ef9ff64 

All other URLs (unsubscribe, tracklink) - (irrespective of trailing slash being there in root URL or not) : **dont work at all for first 4-5 mins and display listmonk login screen i.e. ask username and password** but if this is either refreshed continuously or left as it is for 4-5 mins - they magically start working

**Comment by jackdanielux** [comment]
I have finally figured out the issue, without NGINX also the same issue persists @knadh The URLs using Tracklink and Unsubscribe URL don't work immediately on sending the email i.e. I sent out the email and immediately opened it and then tried to click on the URL.  It still asks me for the password.   Same issue i.e. after 4-5 mins, it starts working properly.  Do you have some sort of cron running at the backend to actually create those URLs or are these immediately written in the DB at the time of link insertion using tracklink feature?  My assumption that NGINX was NOT doing this actually got confirmed when I did a fresh install of listmonk on a non nginx droplet and tried emailing (without SSL) using the port visible as the public URL..

**Comment by jackdanielux** [comment]
@knadh : Tried with earlier versions as well, same issues.  Same is the error that this issue notes : https://github.com/knadh/listmonk/issues/100

In case you want to reproduce this, this is what I followed:

- Create DO Droplet, Login to SSH, Install Postgres (create user, db)

- Create dir listmonk, enter the directory, wget https://github.com/knadh/listmonk/releases/download/v0.7.0-alpha/listmonk_0.7.0-alpha_linux_amd64.tar.gz, unpack the zip

- ./listmonk --new-config to generate config.toml. Then, edit the file.

- ./listmonk --install to setup the Postgres DB 

- Run ./listmonk and visit http://domain.com:9000 > change the root URL to http://domain.com:9000 so that all URLs open with the correct root URL (only opt-in works like this)

- Run campaign, open email immediately and try clicking link of unsubscribe and other tracklink (both wont work) - If you restart the server the links start working immediately, otherwise all links will start auto-working in next 4-5 mins.

Issue does not seem to be there with NGINX routing (since I did not install NGINX).  May be a cron is running at the backend to write these tracklink URLs in the DB and it runs only every 5 mins thus the explanation, but the same explanation beats the logic why Unsubscribe URL won't work for that user (since the Unsubscribe URL remains the same).

**Comment by knadh** [comment]
This is really strange. We have never spotted this in production and we have millions of subscribers on the instance. Let me try and reproduce this on a DO instance.

>  May be a cron is running at the backend to write these tracklink URLs in the DB and it runs only every 5 mins thus the explanation.

All DB writes are instant. The 404 means there's something wrong with HTTP routing. Let me investigate.

**Comment by jackdanielux** [comment]
Thanks.  Pls find below my config file if that helps in decoding this error:

[app]
    # Interface and port where the app will run its webserver.
    address = "0.0.0.0:9000"

    # BasicAuth authentication for the admin dashboard. This will eventually
    # be replaced with a better multi-user, role-based authentication system.
    # IMPORTANT: Leave both values empty to disable authentication on admin
    # only where an external authentication is already setup.
    admin_username = "listmonkusername"
    admin_password = "listmonkpassword"

# Database.
[db]
    host = "localhost"
    port = 5432
    user = "listmonkdbusername"
    password = "listmonkdbusernamepassword"
    database = "listmonkdbname"
    ssl_mode = "disable"

**Comment by jackdanielux** [comment]
Server Config : Ubuntu 18.04/20.04 both tried with Postgres 10/12 - 1GB Ram (5$ Droplet of DO)

**Comment by knadh** [comment]
@jackdanielux I was just able to reproduce this issue on a $5 DO droplet. Surprisingly, I've never seen this locally or in our production. This looks like a routing issue and I suspect it's some sort of a race condition in the HTTP router listmonk uses. Investigating.

**Comment by knadh** [comment]
@jackdanielux https://github.com/knadh/listmonk/commit/1e8b533d45ad6c810d9a569625c1938aaa1d013d fixes this. This fix will be available in v0.8.0 (releasing tomorrow).

Thanks for patiently testing describing the issue.

**Comment by knadh** [comment]
@cb3inco  https://github.com/knadh/listmonk/commit/7a9d11d42613042d9ba0263f24e344312d263c0c fixes the link insertion UI breaking `{{ TrackLink }}`.

**Comment by jackdanielux** [comment]
Fantastic, thanks for this amazing piece of software :)

**Comment by RajuHarry** [comment]
> @jackdanielux [1e8b533](https://github.com/knadh/listmonk/commit/1e8b533d45ad6c810d9a569625c1938aaa1d013d) fixes this. This fix will be available in v0.8.0 (releasing tomorrow).
> 
> Thanks for patiently testing describing the issue.

@knadh  is that released ?

**Comment by jackdanielux** [comment]
Hi @knadh/listmonk <listmonk@noreply.github.com>

Any updates to when can the v0.8 go live?

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/releases/tag/v0.8.0-beta

**Comment by jackdanielux** [comment]
Thanks @knadh 

The URL error seems to be fixed now.  

Below spotted, don't know whether these are expected behavior or bugs:
After doing --upgrade, below changes noticed:

- Any changes to settings done and then click save, it does not save the setting and the app keeps trying to save, then we have to interrupt and refresh the same, now we change any setting, it will auto load the display the changed setting.
- the SMTP details were not stored post upgrade and reverted to default password and my actual username post upgrade ( i figured out when saw logs that SMTP details are incorrect)
- after every successful campaign below is the error noticed in the logs section but the message was successfully delivered to the list:

2020/11/10 18:42:21 start processing campaign (Test 11)
2020/11/10 18:42:21 campaign (Test 11) finished
2020/11/10 18:42:22 error sending message 'Finished: Test 11': 503 Sender already specified.

**Comment by knadh** [comment]
@jackdanielux can you please open a new thread? It's getting quite confusing tracking unrelated issues on this thread :)
