### ISSUE TITLE
Unable to log in after upgrading from 4.0.0 to 4.0.1

### ISSUE THREAD

**Issue by qvnwdra** [knadh/listmonk#2118]
**Version:**
 - Listmonk: v4.0.1 (f5dfb0c 2024-10-28T07:48:58Z, linux/amd64)
 - OS: Ubuntu 24.04

**Description of the bug and steps to reproduce:**
After upgrading from 4.00 to 4.01, I am unable to log in with my previously saved admin user and password.  

Is there any way of resetting the password from the commandline?

**Screenshots:**

**Comment by knadh** [comment]
There's no difference between v4.0.0 and v4.0.1 apart from minor template changes.

That said, to reset the password externally, you can run this query on the database.

```sql
UPDATE users SET password = CRYPT('newpasswordhere', GEN_SALT('bf')) WHERE username='yourusername';
```

**Comment by qvnwdra** [comment]
I reset the password, using the method above, but I am still unable to log in.  

After entering the username and password, I simply get the login screen back.  I cleared cookies, and tried another browser, all to no avail.  

Below is the content of my users table, if that helps.

 id |    username    | password_login |                           password                           |          email          |      name      | avatar | type | user_role_id | list_role_id | status  | loggedin_at |          created_at           |          updated_at   
----+----------------+----------------+--------------------------------------------------------------+-------------------------+----------------+--------+------+--------------+--------------+---------+-------------+-------------------------------+-------------------------------
  1 | listmonk_admin | t              | $2a$06$5wnuHzUg0kGZHLyoTONFfOPYr1PMwLMLxKfdOskABRlLS7N83C2K6 | listmonk_admin@listmonk | listmonk_admin |        | user |            1 |              | enabled |             | 2024-10-29 01:27:17.863768+00 | 2024-10-29 01:27:17.863768+00

**Comment by alorimer** [comment]
I just spent a few hours trying to debug this problem after upgrading to 4.0.1 on Arch Linux.

In my case, the problem was my reverse proxy and an incorrect value for app.root_url. My reverse proxy in Apache worked fine on 3.x but for some reason it stopped working in 4.0.1. My reverse proxy is set up on port 443 only and enforces SSL. However, I had set app.root_url with an http:// prefix, so the login form wasn't being submitted properly. This now makes sense as I got an "insecure connection" warning after clicking submit, but the behaviour still seems a bit strange as I would have expected a connection refused error rather than just going back to the same page.

This seems to be fixed in https://github.com/knadh/listmonk/commit/b995cce5d12973a9b827895d10afab1ffb94ba18 for 4.0.1 but the Arch package hasn't been updated yet.

@qvnwdra were you able to resolve your issue? Maybe it has the same cause as mine?
