### ISSUE TITLE
Reading other variables from config file

### ISSUE THREAD

**Issue by rwilhelm** [knadh/listmonk#212]
Hi,

it seems that only the basic settings are read from `config.toml`. I've tried to add more variables in there, e.g.
```toml
[app]
root_url = "https://listmonk.mysite.com"
```
like seen in https://raw.githubusercontent.com/knadh/listmonk/vue/config.toml.sample.

Am I correct that other variables except the ones produced by `listmonk --new-config` are currently not used?

I've tried using env variables like `LISTMONK_app__root_url=https://listmonk.mysite.com` but it doesn't seem to work, either. Setting up things via the UI works just fine, though.

**Comment by knadh** [comment]
Hi @rwilhelm,
You seem to be looking at an older branch and version. Since v0.7.0, bulk of the config has moved to the settings UI. If you download the latest release and run `--new-config`, [this](https://github.com/knadh/listmonk/blob/master/config.toml.sample) is what you're supposed see.

**Comment by rwilhelm** [comment]
Thank you @knadh,

yes, I'm using v0.7.0-alpha (966954d 2020-10-24T06:13:42Z). Actually I was just referring to that example from the older branch to make it more obvious what I was trying to figure out.

I thought it would be possible to configure listmonkey via a config file _as well_ as via the UI. It's just nice to have configurations for projects in plain files instead of settings exclusively stored away in db tables (is this a feature?). Since listmonkey reads a config file anyway, i thought it would be "natural behaviour" to read other configuration settings from that file as well.

You know, set up the configuration, deploy the thing and it's more or less ready to go without clicking around the UI (which is more prone to human errors).

Anyway, thanks!

**Comment by knadh** [comment]
Hi @rwilhelm. That's how it was until the last version (config + env). As the number of high level settings increased, it didn't make sense for them to be in a config file. That's a usability issue. While technically, it's very easy to override settings from DB with settings from env or files, enabling that would be problematic for usability as what you see on the settings UI is not what would be running, rendering the settings UI unreliable.

**Comment by vlaborie** [comment]
Hi @knadh and thank's for this software !

Some settings like OIDC, S3 storage and even SMTP can be dynamically generated and rotated frequenly (eg. for secret), config from env or config file is a prerequisite for doing that.

If this is only a usability issue, can this be possible to allow all config fron env/toml and disable settings in the UI when a env or toml is set from a specific setting ?

A lot of software doing that, eg. in Mattermost admin UI:

![mattermost](https://github.com/user-attachments/assets/8704620b-a81a-4d89-9f4a-48385e3fcd07)

In Grafana admin UI:

![grafana](https://github.com/user-attachments/assets/bf078325-7647-4699-83f9-55e13c689a41)

**Comment by knadh** [comment]
@vlaborie hadn't come across this pattern, disabling certain config settings on the UI when read from the env. Will explore this.

**Comment by kevincox** [comment]
This is very annoying for us as well. We want to be able to run instances in staging and prod and have similar configuration in both. Right now many settings are only configurable in the DB. For things like SMTP servers, Root URL, uploaded media options and others it is a system administrator's purview rather than a user of the site. While it is nice that these can be easily configurable it would also be nice if there was a supported way to configure these declaratively as part of the deployment rather than user-configurable.

I think the previous suggestion to support env or config file setting and disable the options in the UI is excellent. It is sort of the best of both worlds were the settings are visible and configurable in "pet" instances but can also be controlled easily and predictably by the administrator for automated deployments.

For now I just have a pre-start script that sets all of the correct settings in the database. Not the most elegant and the user can (temporarily) overwrite them but at least ensures that the long-term state is correct.

**Comment by knadh** [comment]
CC @vividvilla. You may be interested in exploring this for a PR.

- Accept all settings variables and env variables (easy with koanf). Eg: `app.root_url -> LISTMONK_APP__ROOT_URL` and so on.
- Merge them into the config loaded from DB (again, easy with koanf)
- Add another `/api/settings/state` handler that returns the list of variables loaded via env, which the frontend can pull and use to disable fields on the UI.
- In the `PUT /api/settings` handler, match the incoming variables against the env variables and if there are any overlap, throw an error.
