### ISSUE TITLE
Feature: Support for S3 storage backend

### ISSUE THREAD

**Issue by mr-karan** [knadh/listmonk#22]
Currently Listmonk stores the uploaded media on the local disk. While this works well, sometimes there might be a requirement of having a remote backend (which effectively makes listmonk as _stateless_). It's more easier to horizontally scale out since there's no volume attached with the app. This is also something the 12factor app [suggests](https://12factor.net/processes). 

I've tried my hands on it and created an interface for the `FileManager` which supports three operations 
- Get
- Upload
- Delete

```
type FileManager interface {
	Upload(string, io.Reader) error
	Delete(string) error
	Get(string) error
}
```

In [uploadFile](https://github.com/knadh/listmonk/blob/master/utils.go#L103) I pass the appropriate `FileManager` (disk/s3) and call the `upload()` method implemented by the interface. 

Issues faced so far: 
- [handleGetMedia](https://github.com/knadh/listmonk/blob/master/media.go#L85) serves the media from the local path, I am unsure how this can be migrated to S3. S3 generates it's own URLs, can I return the same? Downsides will be high bandwidth costs to S3 (but then again, the same is true for any paid CDN)

Before continuing this, I wanted to have a discussion on whether there's interest in adding a remote storage backend?

**Comment by knadh** [comment]
This is great and is something that will definitely be valuable. I initially wanted to do file uploads as a generic blob store, then forgot all about it. For media embedded in e-mails @zerodhatech, we were in fact using assets hosted on a public bucket.

Suggestions:

- Instead of `FileManager`, I think `BlobStore` would a more suitable, more generic interface. It can have Put(), Get(), and Delete().
- It can be a separate `blobstore` package and `models.Media` can move into `blob.Blob` or something. The DB table is called `media`, which is a bummer, as that'll have to change ;( 
- The `blobstore/filesystem` and `blobstore/s3` can be two bundled providers.
- The user can choose one in the config and init can assign it to the global `App`.
- `handleGetMedia()` can just invoke `Get(uuid)` on the BlobStore. It doesn't matter if it comes from the disk or from S3. I don't think bandwidth would be an issue because using S3 as a blobstore would be a conscious choice.

If you're doing this, please consider using something like [https://github.com/rhnvrm/simples3](rhnvrm/simples3) as the AWS SDK is a massive dependency.

Thanks again.

**Comment by vtolstov** [comment]
@knadh how hard to implement embedding media in html? So media content goes via base64 encoded data? I have very small assets and want to embed it inside html.
