### ISSUE TITLE
error connecting to DB: dial tcp: lookup demo-db on 67.207.67.2:53: no such host

### ISSUE THREAD

**Issue by antidamage** [knadh/listmonk#25]
I'm getting this error when following the setup guide:

```
listmonk/listmonk   latest              66e0d30eac19        6 weeks ago         22.8MB

 root  Soundwave  SSH  ~  #  docker run listmonk/listmonk

2019/10/23 14:10:30 main.go:107: reading config: config.toml

2019/10/23 14:10:30 main.go:189: error connecting to DB: dial tcp: lookup demo-db on 67.207.67.2:53: no such host
```

This is running on DigitalOcean with their default docker appliance. Is this an issue with listmonk or DigitalOcean?

**Comment by knadh** [comment]
Can you take a look at https://github.com/knadh/listmonk/issues/21?

**Comment by mr-karan** [comment]
@antidamage Can you post the exact steps to replicate? From where did this `:53` arrive? Usually this port is reserved for DNS (over UDP)

**Comment by mr-karan** [comment]
I see that you're running `docker run listmonk/listmonk` which will only spawn the app container. The setup instructions [here](https://github.com/knadh/listmonk#running-on-docker) mention to use `docker-compose` which will setup the DB also for you. Since there's no `demo-db` container running, you're seeing the error `no such host`.

If you don't want to use `docker-compose`, please create a volume mount with the correct `config.toml` and mount it inside the container which has the correct address/port for where the Postgres DB is running.
