### ISSUE TITLE
List Bombing Prevention via Forms

### ISSUE THREAD

**Issue by jackdanielux** [knadh/listmonk#308]
I don't know if it warrants a thread but trying my luck.  I'm getting list bombed i.e. random emails are subscribed to my double opt in list via form (used listmonk form) because of which my bounce rate is through the roof.  Any way of stopping this, maybe like a captcha etc.?  

Pls suggest simple methods.

**Comment by knadh** [comment]
hm, captcha needs a serverside check. Not ideal, but as a simple stopgap measure, you could put your domain behind Cloudflare. CF does a good job of detecting and stopping bots.

**Comment by mdehollander** [comment]
This week I am experience also signups via bots on one of my listmonk instances, causing a lot of delivery failed messages because these accounts are locked by the email providers because they receive too much emails.

I am not a big fan of putting a website behind a cloudfare cdn, also because it attract mostly visitors from a single country, although I read that cf does indeed a good jobs in blocking ip's of spam bots. However, there are also some alternatives that can be implemented on the server side. Could you maybe consider to implement a Honeypot field and reject requests that gave filled in that field? This would maybe be a first good first protection layer. For an example concept see https://stackoverflow.com/questions/36227376/better-honeypot-implementation-form-anti-spam

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/fe61e898a3c5ae6c5fefbd7ee65a995629cef2e7 : Added a simple honeypot check with a hidden field.

**Comment by jackdanielux** [comment]
Thank you for this 👍

**Comment by MaximilianKohler** [comment]
>Added a simple honeypot check with a hidden field

Is this automatic, or is there something we have to do to use this?

**Comment by knadh** [comment]
It's automatic, but it's easily beaten by "smart" bots. The only robust solution here is enabling hCaptcha.
