### ISSUE TITLE
Prevent app from update

### ISSUE THREAD

**Issue by brunowego** [knadh/listmonk#326]
I'm behind a proxy where I not have access inside my cluster to internet.

**Comment by mr-karan** [comment]
Updates are opt-in. Unless you pull the latest image, you can keep running a fixed `listmonk` version.

**Comment by knadh** [comment]
Ah, you mean update checks. Makes sense to add this.

**Comment by alerque** [comment]
Thanks, this option is appreciated ... but the implementation has a loophole. This is something that really needs to be implemented as a CLI flag/config file option so that it can be disabled before the first run, not after! With this implementation there is a bootstrapping issue in that it can only be disabled after its already been run.

**Comment by alerque** [comment]
Another option if you are adamant about keeping it out of the system config file would be to default it to off.

https://github.com/knadh/listmonk/commit/95a81d17ced9766d40447364de12925b51c844fd#diff-939acd018b931292330e519becd8d003ed0dd20c5e42de62ec3d37553698739aR181

**Comment by knadh** [comment]
The toggle on the UI is more accessible for most users. Defaulting to off means most users would end up missing out on updates.

Right now, the update check happens a) on boot b) every 24 hours. If "check on boot" is disabled, then listmonk will only check for updates after 24 hours of boot, which should solve this problem. This can be done trivially.
