### ISSUE TITLE
Config option for static-dir is conflated with other assets, can't be used without setting CWD too

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#361]
I appreciate the attempt to fix #340, but in my testing of the 1.0.0 release it is not actually fixed.

Mind you the console log message are different, but it doesn't actually work.

1. From *inside* the /usr/share/listmonk directory
   - launching works with no argument as before
   - launching with `--static-dir /usr/share/listmonk/static` echos a message to the console that suggests it is using that path (which is different than with no argument
   - launching with `--static-dir /usr/share/listmonk` fails saying it can't find "email-templates" suggesting that this argument really does want the "static" folder, not the parent directory where it currently needs to be launched.
   - launching with `--stataic-dir /foo` fails with an error, suggesting that it's actually using that to load email tempaletes
1. From any other PWD, e.g. `cd /tmp`:
   - launching with no argument fails (as before)
   - launching with `--static-dir /usr/share/listmonk/static` fails with an error that "config.toml.sample" does not exist. First of all, given that I'm also passing `--config /etc/listmonk/config.toml` who cares about the sample file! Why should it even be looking? Second this file isn't in the "static" directory, it's in one directory up from there, suggesting the argument doesn't know what it wants to be.
   - launching with `--static-dir /usr/share/listmonk` fails with an error that "config.toml.sample" does not exist. Again it still doesn't find this file, which also suggests it wont' be able to find the i18n or sql files there either.
1. ~~No iteration of setting `static_dir` in the config file seems to have any affect as was suggested in earlier comments. The log messages don't reflect the same results and the `--static-dir` CLI arg, they reflect the same results as not having an argument at all.~~ Still a documentation issue, this does work but the key is `static-dir` not `static_dir`.

This needs more work:

1. ~~Check the CLI flags first, then the config file.~~ This may be working, but it's hard to tell with the setting itself not working.
1. Stop looking for sample config files if it's not used for anything
1. Add another setting if necessary for where the run time files like i18n that are that are not "statics" in the sense of user-editable templates. Perhaps statics should be renamed to "templates" and a new setting for other runtime assets that should not be edited but always come with the package should be added.
1. Use static assets from the specific setting if present, then fall back to the runtime directory (can be a distro installed bath) or lastly the embedded system. It should be possible for users to customize this without changing anything in their distro's installed path while still using a file system path for distro packages (no embedded files).

**Comment by knadh** [comment]
> Stop looking for sample config files if it's not used for anything

It is used by `--new-config` and hence, is a part of the app.

When no embedded static files are found, it is an abnormal release as far as the app is concerned. Static embedding is a clearly defined build step and that is how binaries are distributed for all platforms in official releases.

In this abnormal scenario (it's only normal and expected in a development environment), it's fair that the app expects its critical static files in the current working directory. This is working as expected. The only exception is `--static-dir`, which was always an additional feature because external templates were meant to be customizable. With the recent fix, this flag also works as expected.

I don't think it is necessary to add more flags to load static assets that really are not meant to be separate from the app. Production binaries should not be without embedded static files. They are a part of the app's core.
