### ISSUE TITLE
The "default" template is only the default half the time

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#362]
There are two completely different templates at play. They start out the same, but as soon as you change one it becomes apparent that the modified one is used sometimes, the original other times.

The static file `email-templates/default.tpl` is used at the start and is what initially fills the database's idea of a "default template." Editing the database one will change the default for campaign emails. It will *not* change the default template used for subscribe messages, etc. For that you have to edit the static `email_templates/base.html`. Which is spiffy, but editing the static file doesn't update the database's default campaign template. The upshot is that to actually change the default template you have to update it it two places.

**Comment by knadh** [comment]
The static files loaded from the disk are for all the non-campaign "system" e-mails and public pages. That is, automatic e-mail notifications, opt-in confirmation mails, data export mails etc.

The templates managed on the UI (stored in the DB) are for sending actual campaigns with custom content. Whatever is created here is what is selected on the UI during campaign creation.

**Comment by alerque** [comment]
As an end user this is about as clear as mud and took dozens of experimental messages, lists, campaigns, and users to navigate. There are at least three different templates containing at least large chunks of the same content for optin confirmation messages, and those content chucks can even end up in different templates depending on whether users sign up themselves or get sent an optin campaign.

Just to make things more confusing, some otherwise identical templates are inside out and some are outside in — which affects what Go templating escapes need to be done. I've been trying to keep them in sync with the same content but have to remember to tweak the escaping and test all variants after every change.

There should be fewer templates and more clear delineations for what is used where.

**Comment by knadh** [comment]
I've just [documented system templates](https://listmonk.app/docs/templating/#system-templates) and described the template files individually.

> There are at least three different templates containing at least large chunks of the same content for optin confirmation messages

There are two files and they are drastically different in functionality. They cannot be combined. One is a stand alone template and the other gets inserted into an optin campaign body.

> Just to make things more confusing, some otherwise identical templates are inside out and some are outside in — which affects what Go templating escapes need to be done. I've been trying to keep them in sync with the same content but have to remember to tweak the escaping and test all variants after every change.

I'm not sure what this means. Inside and outside?

> There should be fewer templates and more clear delineations for what is used where.

There are as few templates as possible and I cannot think of any files that can be removed.

> As an end user this is about as clear as mud and took dozens of experimental messages, lists, campaigns, and users to navigate. 

Sorry that that was the case, but as no other user has ever brought this up, so I would presume that it's not that drastic a case of confusion. What is created on the UI under Campaigns -> Templates (DB) is what is used in Campaigns and that's obvious because there's a selection box that appears with the list of templates the user has created on the UI.

Also, in my personal time that I invest in building and maintaining this project for free, I don't really have the cognitive bandwidth to process passive aggressive comments :) I appreciate the detailed feedback you have been posting and I've promptly addressed pretty much all of them, but it would be great if we could keep the language concise. I don't think it's fruitful to discuss and debate every minute aspect of the app. A request for documenting the system template files would've been sufficient for this issue rather than passive aggressive remarks such as `"clear as mud"`, or `"... only the default half the time"` (which is clearly not the case. There is only one default and that is the DB one.), or a patronizing statement like `"There should be fewer templates and more clear delineations for what is used where"`. Why would you assume that the author hasn't thought about such a fundamental facet?

I haven't taken offense. Just saying that we can use the time spent on this project fruitfully! :tangerine:
