### ISSUE TITLE
Todo: Analytics / reporting view

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#391]
- Standalone analytics page that allows selecting one or more campaigns.
  - Plot views.
  - Plot clicks.
- Modal view on subscribers.
  - Plot views.
  - Plot clicks.
- Export reports as CSV?

**Comment by roshanjonah** [comment]
Views and clicks as percentages on the campaign page maybe?

![Campaigns___Email_It_App](https://user-images.githubusercontent.com/20136098/121968245-11c0d180-cdc6-11eb-868e-30960a545811.jpg)

**Example:**
Views 32706 (1.88%)
Clicks 3251 (9.94%)

I used views as the basis for calculating clicks percentage as some ESPs do because you can't click on what has never been opened + looks better (given we don't consider the small number who don't download the image but click on the links).

Also adding bounces/unsubscribes/complaints stats to the campaign page would be helpful since the v2 release includes bounce processing :)

**Comment by knadh** [comment]
A dedicated page for plotting and comparing views, clicks, and bounces for N campaigns.

![image](https://user-images.githubusercontent.com/547147/132989529-6fdd44e6-1ef1-47fa-a557-744f15c3387e.png)

**Comment by knadh** [comment]
This is now merged into master (https://github.com/knadh/listmonk/commit/61e88681edc02a31004f7f08d3735cdf06be42d8) and ready for release in v2 (~this week).

**Comment by Waelsabry36** [comment]
does it will contain the Standalone analytics page that allows selecting one or more campaigns.
Plot views.
Plot clicks.
Modal view on subscribers.
Plot views.
Plot clicks.
Export reports as CSV?

**Comment by MaximilianKohler** [comment]
Suggestions:

* See people your campaign was not delivered to: IE: 

>I see in the AWS console (suppression list), that bounce-test@service.socketlabs.com has already been blocklisted. When I send a campaign to them it would be important to know that it was never delivered to them.

* Add per-campaign, unsubbed, blocklisted, and complained stats. I guess "complaints" relies on #497 though.

**Comment by FelipoAntonoff** [comment]
It would be interesting to have this data per customer, so you can have a general summary of it and per campaign and send.
