### ISSUE TITLE
Sending individual emails

### ISSUE THREAD

**Issue by althaf004** [knadh/listmonk#407]
Is it possible to send individual mails upon registration/ forgotpassword/  or any actions using listmonk ?

**Comment by knadh** [comment]
Transactional mails, not yet. However, it's being planned and might land in the next version or the one after. The issue's been tracked here: https://github.com/knadh/listmonk/issues/42

**Comment by s-kris** [comment]
Thanks @knadh Transactional email support will be great. 
1. Create a template with params.
2. API call with the template id (+ params) to an array of emails, list of users or dynamically pick users via api.

**Comment by knadh** [comment]
Transactional messaging support was just added in the v2.2.0 release.

**Comment by s-kris** [comment]
Thank you @knadh :)

Looks like `/api/tx` accepts one email instead of array. Is it possible to add support for email array.

**Comment by NicoHood** [comment]
I've read multiple times about the transactional messaging, but never found a lot of background information, just the API. What is this "thing"?

**Comment by knadh** [comment]
@s-kris possible, but simpler to keep it one per transaction. One message to a subscriber, one transaction. The transactional data is going to differ from subscriber to subscriber anyway, otherwise, it'd be a campaign.

@NicoHood when you order something from an ecommerce platform, you get an order confirmation e-mail with specific data in it. It'll be the same e-mail for all orders, but transactional details like order ID, timestamp etc. varies. That is an example of a transactional message.

In listmonk, you can create a transactional template like that (in the Templates section) and use the new `/api/tx` API to fire off an e-mail to a subscriber whenever there's a transaction of some kind. You can pass arbitrary transactional data to be injected into the template, and you also get to use information on the subscriber's profile to use in the e-mail like you do with campaigns.

**Comment by NicoHood** [comment]
That sounds like an email marketing feature. But it cant be used with the UI, just for custom builds, right?

**Comment by knadh** [comment]
Transactional messages are distinctly different from marketing e-mails. They're used for sending details of transactions (like a purchase or a financial transaction), password reset e-mails, notifications etc.

**Comment by jarzi25** [comment]
Hi @knadh,

I was trying out the transactional e-mail API using the `curl` command show [here ](https://listmonk.app/docs/apis/transactional/) and it worked perfectly. 

But when I tried to send an e-mail to a user who is not a subscriber in `listmonk` then I started getting an error `{"message":"Subscriber not found"}`.  I tried this to check if I can send a "Welcome" email to a new user who is not added as a subscriber yet.

Can you please let me know if it is possible to send an email to user who is not a subscriber.
