### ISSUE TITLE
Bundle sysytem unit file in the repo

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#411]
> I’d be nice to have a default systemd unit file as part of the project that can serve as a basis for package maintainers. systemd provides a lot of options that reduce the attack surface of an application and it would be nice if we could document any practical and applicable options right here, so they’re discoverable for everyone.

Ref https://github.com/knadh/listmonk/issues/409

**Comment by knadh** [comment]
@kmohrf please feel free to send a PR.

**Comment by kmohrf** [comment]
Can you shed some light on how the paths are constructed? The default value for uploads in the database is `uploads`. Is that a relative directory? If so: to which directory is it relative to?

One of the most useful options for hardening a systemd service would be to use the `DynamicUser` directive. In that case systemd will create a user on-the-fly when starting the service and assigns a state/home directory to it. This state directory is kind of predictable but i guess it would help if the upload path field would either support the `$HOME` env variable. In case directories are relative to the users home it should work out-of-the-box.

**Comment by knadh** [comment]
By default, the path is `./uploads` and it is relative to the binary's CWD, whichever path the bin is run from. This is just a placeholder and users are expected to create a directory and update the path in the settings UI. listmonk by default does not create an `uploads` dir, so without explicit user action, uploads don't work.

> This state directory is kind of predictable but i guess it would help if the upload path field would either support the $HOME env variable. 

If this works `https://golang.org/pkg/os/#UserHomeDir`, we can consider adding support for a home `$HOME` placeholder in all path fields on the UI. Would you be able to check if this function returns the correct path when run as a `DynamicUser` in systemd?

**Comment by kmohrf** [comment]
> By default, the path is ./uploads and it is relative to the binary's CWD, whichever path the bin is run from.

Maybe I’m just confused but that seems contradictory? I install listmonk to `/usr/share/listmonk/listmonk` the binary itself and the directory are owned by root and are not writable by listmonk. I start listmonk from `/var/lib/private/listmonk-foo` (my CWD) with `/usr/share/listmonk/listmonk --config /etc/listmonk/foo.toml`. Would the default upload path refer to `/usr/share/listmonk/uploads` or `/var/lib/private/listmonk-foo/uploads`?

> If this works https://golang.org/pkg/os/#UserHomeDir, we can consider adding support for a home $HOME placeholder in all path fields on the UI. Would you be able to check if this function returns the correct path when run as a DynamicUser in systemd?

I guess so. I’ll give it a try!

**Comment by knadh** [comment]
It will refer to `/var/lib/private/listmonk-foo/uploads` if the value is just "uploads", your CWD. But like I said, the user is expected to:

a) create a directory for uploads somewhere.
b) put that path in settings `/var/lib/private/listmonk-foo/uploads`.

**Comment by kmohrf** [comment]
I get that users are supposed to configure it, which is fine for listmonk itself where you can’t make a lot of assumptions about the environment. With the systemd unit we can make a few assumptions because it partially defines the environment and making sure the uploads directory works out-of-the-box seems attainable and helpful :).

@alerque you’ve explicitly set the `TasksMax` and `LimitNOFILE` options in the ArchLinux systemd unit. I don’t have a lot of reason to deviate from the OS defaults, but I also don’t have a lot of experience running listmonk as a service so if you have some insights as to why you’ve set them and what made you choose their respective values, I’ll add these options as well.

Other than that I’m pretty much done with testing my systemd unit and it only needs some documentation. Expect a PR soonish :).

**Comment by alerque** [comment]
@kmohrf Sorry I don't have much useful to say except that those two settings came from some other similar daemons that I thought might run into similar issues with defaults. I suggest going with distro defaults unless you have a better reason than that to change them.

I'm aware there are several hardening things that could/should be done here and my service file didn't show any effort in that direction yet. I was fighting other problems with listmonk's assumption that it has embedded files in the binary and is run from where otherfiles are located.

By the way are you baking in the resource file set into the binary? Also supplying them in plain sight in `/usr/share` or somewhere?

**Comment by kmohrf** [comment]
I’m using the `dist` make target and bake everything into the binary. This probably wouldn’t be allowed in a real deb package, but I’m not a debian developer and I’m not doing an official package so I get a pass :). I like that users can use the app without a web server running on the same host, which would have been necessary otherwise to serve the assets. The only thing I include in the deb package in plain sight is the static dir with the templates, because I guess it’ll be quite common for people to override those.

**Comment by alerque** [comment]
I don't think a web server is *required* either way, the `listmonk` daemon handles reading the files and serving the content whether from the embeded assets or the file system. Frankly a web server proxy is kind of the assumed setup (especially for SSL termination), but I don't think the baked-in approach is what enables that to be optional.

**Comment by kmohrf** [comment]
Ah I didn’t realize it will serve files whether they’re backed in or not. Then I’ll add them to the file system I guess. I use listmonk with NGINX doing TLS but they’re in separate virtual machines. If listmonk would only serve files that are baked in, that would have meant that there **had to be** a second web server on the same host as listmonk but this way it’s perfect. Thanks for bringing it to my attention! :)

**Comment by knadh** [comment]
@kmohrf Why is a self-contained binary a problem though? Many apps are self-contained. Not sure how Debian packaging wild have an issue with the structure of a binary.

**Comment by kmohrf** [comment]
Greatly simplified: Debian does not like (and I think still does not and never really will allow) dependency bundling. Even the vue build process that bundles JavaScript dependencies is a problem in that regard. This has been a packaging problem for years now, because more and more application started using bundlers like webpack compared to simple `<script src=...></script>` references in the HTML that were easy to resolve. Debians position on this basically is: every dependency (including everything in the dependency tree) must be available as a deb package. Last I checked the way-to-go was to bundle on installation and on dependency updates. You have to remember that operating systems like Debian provide security by allowing packages to be replaced at runtime. That means: security issue in dependency X will lead to a security update for that specific package and depending libraries or application are either dynamically linked and will be restarted (in case of applications) or need to define an *interest*-trigger and do rebuilds. This is great for anything traditional like desktop and server applications but very tedious for web applications with hundreds of dependencies. There have been some new developments like the establisment of the *fasttrack* repository for software that moved on from the more traditional release cycles and does release-early-release-often, but I’m not up-to-date on the current developments (as I said I’m not a Debian developer nor maintainer).

If listmonk is going to get official Debian packaging I think they will first package the Go application and split the vue frontend into a separate package (if they would package it at all). This is probably what I will do too, know that I know, that there’s no need to bundle the assets. I’ll just ignore the issue with the bundled dependencies. But if you’re keen on getting into Debian we can write up a request for packaging and I think some of the changes we’ve made are beneficial for any packager :)!

PS: Don’t take anything I’ve said about Debian policy as the absolute truth. There’s has been quite some movement in this regard and though I do a lot of packaging for *free software* as well as closed-source private- and work-related software, it’s quite complex and hard to stay on top.

**Comment by knadh** [comment]
Ah, I didn’t realise static assets of a web app were considered “dependencies” in the same vein as libs in the Debian world! That seems almost impractical to implement for web apps with arbitrary static files.

Are there examples of such packages you are aware of? I could think of consul off the top of my head. It’s a Go app that also has a web UI. Will have to check how the package is structured.

https://packages.debian.org/buster/consul

**Comment by kmohrf** [comment]
I guess not necessarily *your* static assets but everything you depend on. In case of listmonk buefy would constitute a dependency so it should be packaged separately in Debian. At least, that is my understanding (with all the package versioning hassle this entails).

I can’t find any static assets in the consul package and installing it in a vm and navigating to the UI like [it’s explained in the docs](https://learn.hashicorp.com/tutorials/consul/get-started-explore-the-ui?in=consul/getting-started#navigate-to-the-ui) yields a 404. So I guess they stripped the UI? The same is true for the [buildbot](https://packages.debian.org/buster/buildbot) package. It’s just the server process, no UI.

**Comment by kmohrf** [comment]
While looking at the possibility to externalize the static files in my deb build I noticed that listmonk tries to resolve static filepaths relative to the current working directory (`config.toml.example`, `queries.sql`, `schema.sql`, ...). May I suggest to change that to the directory path of the *realpath* of the listmonk binary? This way the current working directory can be used for variable files (like uploaded content) and the directory where the listmonk binary is placed is used for static data, that the average user won’t normally modify.

"directory path of the *realpath* of the listmonk binary" because I’d install the listmonk binary to `/usr/share/listmonk/listmonk`, symlink it to `/usr/bin/listmonk` and place any static files into `/usr/share/listmonk`. Without the realpath static files would be expected in `/usr/bin`.

**Comment by knadh** [comment]
Yeah, looks like the Consul UI is stripped.

I was looking at this https://wiki.debian.org/Packaging/ComplexWebApps - It cites GitLab as an example for a complex web app packaged for Debian.

**Comment by kmohrf** [comment]
Yeah, the gitlab package has been a source of some… let’s call it… friction in the debian world :)

**Comment by alerque** [comment]
GitLab is a disaster to package for distros. I‌t was a nightmare to setup in the first place (I was the original packager in the AUR before it moved to [community] and although it has been through many other hands since am now back involved with it again) and an ongoing source of frustration for packagers since. On the Arch side there wasn't so much internal "friction" so much as lots of frustration and not-so-good feelings towards the upstream.

**Comment by kmohrf** [comment]
I think this one can be closed now that #417 is merged.
