### ISSUE TITLE
For campaigns, need to know the current status and an acknowledgement upon 100% completion

### ISSUE THREAD

**Issue by guruduttgaitonde** [knadh/listmonk#460]
We need to know if any campaign failed or stuck. For stuck, we need progress values so if we poll with some interval, we will know that if progress value is equal to last one then that means campaign is stuck

**Comment by knadh** [comment]
https://listmonk.app/docs/apis/campaigns/

In the `GET /campaigns` API response, you can use the `to_send` and `sent` values to compute the percentage. `to_send / sent * 100`.

**Comment by guruduttgaitonde** [comment]
Thanks for the quick response. Just another question, say for example, we
send a particular campaign to multiple recipients and that campaign gets
stuck, (few recipients receiving the campaign and others do not). For us to
implement a retry mechanism,would that mean simply resending the campaign
to all the recipients (including those who have received the campaign, so
duplicate campaigns would be received by some recipients) or is there an
intelligent way within listmonk to handle retrials?

Thanks and regards,
Gurudutt Gaitonde
TM Investment Technologies Pvt. Ltd.

**Comment by knadh** [comment]
Each mail is retried multiple times (configured in the SMTP settings) before it is considered failed, and after that, it gets added to the error threshold which causes a campaign to be paused. Currently, there is no way to retry the e-mails that fail after multiple retries, so when you resume a campaign, the failures that lead to the pausing do not get attempted again.

If your campaigns are getting paused because of errors, that means there are serious issues with the upstream SMTP. You can set a low error threshold (`Settings -> Performance`) to reduce the misses.
