### ISSUE TITLE
Add Custom Attributes to users in form

### ISSUE THREAD

**Issue by code3z** [knadh/listmonk#536]
Here is my code:

```
                <p><input type="email" class="nq-input" name="email" placeholder="Email" /></p>
                <p><input type="name" class="nq-input" name="name" placeholder="Name (optional)" /></p>
                <p><input type="text" class="nq-input" name="website" placeholder="Website (optional)" /></p>

                <p class="text-center">
                    <input id="8c3cb" type="checkbox" name="l" checked value="8c3cb42c-6ded-43d7-b5ed-27121497bed8" />
                    <label for="8c3cb">Get Notified</label>
                </p>

                <p><input v-ripple class="nq-button" type="submit" value="Subscribe" /></p>
```
How can I allow the user to specify their website and have it show up as a custom attribute?

**Comment by TIMBLOCKER** [comment]
Hi knadh,
there seems to currently be no easy way, but it is very inconvenient having to develop your own frontend with the respective endpoints. 

It would be really great if there was an easy way to add custom fields to the signup form (i.e. numeric, string(maxLength), boolean). These could be typechecked to make up for the aforementioned security concerns before entering them as JSON payload.

This feature seems to have a valid use and great impact on the usability, as users can rely more intensively on listmonk instead of having to administrate another database with the respective fields (I want to be using it as a mail tool for my local triathlon team and we have a need to admin some ids and other fields). I get your point of having to deal with security. Maybe you could reconsider allowing this (maybe in an experimental mode?) so that this feature can be used and administrated.

Thanks for the great tool!

Tim from Germany
