### ISSUE TITLE
Can we support MySQL?

### ISSUE THREAD

**Issue by hsluoyz** [knadh/listmonk#60]

**Comment by knadh** [comment]
Just responded to your question on the older thread https://github.com/knadh/listmonk/issues/17#issuecomment-586595895.

**Comment by heyakyra** [comment]
> Also, listmonk relies heavily on Postgres features such as JSON blob and indexes. I don't think the complexity of supporting multiple DB backends is beneficial.

https://github.com/knadh/listmonk/issues/17#issuecomment-528785042

Many users have multiple services running on the same server, and most services tend to be using mariadb/mysql. It's more resource intensive to have to run both side-by-side.

**Comment by knadh** [comment]
@heyakyra This is not on the cards for now as there are many other essential, fundamental features that are yet to be built and integrated. Maybe once those are done and listmonk enters beta, an abstraction for multiple DB backends could be considered.

Adding support for MySQL is not trivial work.

**Comment by nischay876** [comment]
Please add mysql support there are many good mysql hosting like oracle free tier provides 8gb ram and 50gb storage db forever free so mysql is like a basic need or atleast [SQLite Support #368](https://github.com/knadh/listmonk/issues/368) is needed because why host 2 containers when u can just run it using one
