### ISSUE TITLE
Workflow/way to work with ListMonk

### ISSUE THREAD

**Issue by olivierlambert** [knadh/listmonk#642]
Hello there,

First, I'd like to thank you for this great software. I'm also a great free software fan (as well as a pretty big contributor in another software). So I know the amount of work needed to make it real.

I have various non-technical questions on the "right" way to use it, without really bending it too much. It seems to be a great replacement for Mailchimp, so for "classical" subscription forms and campaigns, I think I got it. But what about other cases:

1. Could it be used for an "external" automated email system thanks to its API? Let me explain: like for a current app we have, we'd like to leave the email management outside. Concrete example: I have a template in ListMonk for a "password recovery email", with some variables. I would imagine my current app to create the user in Listmonk with extra attributes (like the token for password recovery) and inject it in my password recovery email template, then ask Listmonk to send it. Is it doable?
2. How far the template system can be used, I mean for what I've seen, it's mainly to get the overall design (header/footer). Would it be "logical" to go even further, eg a template we can use to announce our monthly release: it's always the same aspect, with a list of features and so on. To ease the work of marketing so they can just replace stuff in the template "visually" by the right values.

**Comment by knadh** [comment]
Thanks @olivierlambert. 

1. listmonk is designed to be a campaign based mailing list manager and isn't ideal for individual, non-campaign transactional e-mails right now. However, since pretty much all the pieces required to send an individual transactional e-mail is available in the core, I've in fact been working on a branch that offers exactly what you've described. This will be available in the next version (this month). An API that can trigger a message using any template with an arbitrary recipient and variables.

2. The templating system uses full fledged Go templates, so they can be as complex as you want. [sprig](https://masterminds.github.io/sprig/) is also bundled, which offers even more functionality. However, the templating functions are for composing messages and reside within messages. They cannot be used for creating external automation that triggers e-mails. If you are looking for automation, maybe something like [Mautic](https://www.mautic.org) may be better suited.

**Comment by olivierlambert** [comment]
1. Wow! Nice timing then :partying_face: That's exactly what we will need! I'll be happy to test and report!
2. I understand, and it's fine :) I'm trying to make sense of the diff between Mautic and Listmonk :thinking: At some point, it seems similar, but Mautic provides automation/logic while ListMonk focus on get users registered to a list of contact for later mass mailing? Is that right?

Also, again: a big thanks for this project!

**Comment by knadh** [comment]
> I'm trying to make sense of the diff between Mautic and Listmonk thinking At some point, it seems similar, but Mautic provides automation/logic while ListMonk focus on get users registered to a list of contact for later mass mailing? Is that right?

That's correct. Mautic is a "marketing automation tool" while listmonk is a list manager. The [screenshots here](https://kb.mautic.org/knowledgebase/campaigns/creating-campaigns) gives an idea of what the core proposition of Mautic is.

**Comment by olivierlambert** [comment]
That's more clear now, thanks! So at some point, they might be complementary? (does it make sense to use both if needed). Sorry for all those questions :)

**Comment by knadh** [comment]
Yep, both can be complementary. If you foresee handling a large number of subscribers, you may find a setup like what we do at work useful. We use listmonk for managing our mailing lists with millions of users (sending important updates and newsletters), and Mautic for doing things like sending a reminder e-mail / Whastapp message to a user if they've paid while signing up on our website, but haven't finished the required steps after that.

**Comment by olivierlambert** [comment]
That makes sense to me, your setup is a good example we'll have to follow I think (we have 90k+ subscribers already).

Should I close the issue for the original request or you want to close it while you release the new feature?

**Comment by knadh** [comment]
Thanks @olivierlambert. Closing this issue as transactional messaging is being tracked here https://github.com/knadh/listmonk/issues/42
