### ISSUE TITLE
E-Mail template not updated on listmonk version 2.1.0 upgrade

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#780]
**Version:**
 - listmonk: 2.0.0 to 2.1.0 upgrade

**Description of the bug and steps to reproduce:**
I [just noticed that I am missing the most up to date listmonk email template](https://github.com/knadh/listmonk/commit/4ddd3e803ff589ea35e768d37c46faeea2c81b5d#commitcomment-71553935). It seems to be not being upgraded in 2.1.0.

I could manually fix this by pasting the new template. This should be added to the upgrade guide: https://github.com/knadh/listmonk/releases/tag/v2.1.0

Woudn't it make sense to add a "Standard Template" (not default) that you cannot edit, just show & copy? Then we could always override this on an upgrade.

**Comment by knadh** [comment]
Automatically upgrading a template is infeasible. Changes are rare, but yes, it should've been documented in the release notes.

An undeletable resource is annoying on the UI. Also, it wouldn't solve the problem because a user has to be still told to copy and use such a template in case of a change, which in most cases wouldn't make sense, because users will just have to edit their custom templates anyway.

**Comment by NicoHood** [comment]
I do not think that many people would edit their template. I have no better option yet than locking the default template. Maybe someone else has more opinions on that?
