### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by lunardigital** [knadh/listmonk#8]
Integrate with 

https://github.com/c1982/bomberman
https://github.com/trumail/trumail

Also something where we can send extremely fast using SNAT/DNAT iptables stuff. 

Cloudflare API to generate DKIM etc and push to domains. 

create advanced list segmentations. 
Opener IP to email etc relations. 
TCP-SMTP Proxy server can work aswell.

**Comment by lunardigital** [comment]
Dynamic DNS Updates for the mailserver / mx record and ips. 

Can use Heroku to get many ips to start cleaning databases. 
or AWS Lambda. 

List Management extremely important. 
ip2loc include. 
and referrers and drop into relations with emails.

**Comment by knadh** [comment]
Can you elaborate a bit on these? It sounds like many of these can be orchestrated externally without adding anything to listmonk's core.

To provide some perspective, listmonk is a mailing list manager and does not aim to be a marketing tool. It exposes pretty much all its functionality and all its data as APIs (and the DB schema is simple to read directly from) so that it can be integrated with external systems, including marketing tools.

**Comment by lunardigital** [comment]
so API Centric.
