### ISSUE TITLE
issue while uoloading media 

### ISSUE THREAD

**Issue by ChaudharyG** [knadh/listmonk#894]
**Version:**
 - listmonk: [eg: v2.1.0]
 - OS: [e.g. Centos]

Hi Team we are facing error while uploading media. 

**Screenshots:**

![image](https://user-images.githubusercontent.com/15512968/182564651-a46b17c9-bd39-4cc7-886b-36e077e6c10e.png)

![image](https://user-images.githubusercontent.com/15512968/182564847-06f3f530-c17e-4c68-8d54-3e5401f8eb12.png)

![image](https://user-images.githubusercontent.com/15512968/182565386-0113e18f-d516-4c1e-a785-efacda5e0793.png)

Please help me with steps to solve the issue. 

Please guide me how to mount the upload folder to the container

Thanks in advance

**Comment by knadh** [comment]
Shouldn't it be `/home` instead of `./home`? Does that directory have proper permissions?

**Comment by ChaudharyG** [comment]
update : 

![image](https://user-images.githubusercontent.com/15512968/182573345-052831d3-253d-4d3e-a220-9df1efd023fd.png)

Settings : 

![image](https://user-images.githubusercontent.com/15512968/182573571-b0fccd89-64f6-4e02-bbec-8e6f00cb4b8e.png)

Error is still same : 

![image](https://user-images.githubusercontent.com/15512968/182573719-c5b85503-504e-43f5-9b09-a3d9f920ca86.png)

**Comment by knadh** [comment]
@mr-karan would you be able to take a look, please?

**Comment by ChaudharyG** [comment]
We check all the setting, but still no luck

**Comment by mr-karan** [comment]
@ChaudharyG You've two options here. 

1. Using `docker volumes` 

For doing that, you can add the following config to `docker-compose.yml`:

```yml
app:
    volumes:
      - type: volume
        source: listmonk-uploads
        target: /listmonk/uploads

volumes:
  listmonk-uploads:
```

This volume is managed by `docker` itself, and you can see the host mount path with `docker volume inspect listmonk_listmonk-uploads` 

You can see files are uploaded correctly here:

```
root@pop-os:/var/lib/docker/volumes/listmonk_listmonk-uploads/_data# ls
nick-martin-JYdvvB_Qy7Y-unsplash.jpg  thumb_nick-martin-JYdvvB_Qy7Y-unsplash.jpg
root@pop-os:/var/lib/docker/volumes/listmonk_listmonk-uploads/_data# 
```

2. Using `bind mounts` 

You can simply do this:

```
    volumes:
      - ./uploads:/listmonk/uploads
```

The  issue you're facing is because you're giving the path as `/root/listmonk` which doesn't exist in the container. So, either you need to `mkdir -p /root/listmonk/uploads` or the better option is mount it inside `/listmonk/uploads` only so it'll work with default settings.

**Comment by mr-karan** [comment]
@knadh I've sent a PR to add docs for media uploads with docker: https://github.com/knadh/listmonk-site/pull/27

**Comment by ChaudharyG** [comment]
Sorry but still my upload is not working ...

**Comment by MaximilianKohler** [comment]
> Sorry but still my upload is not working ...

@ChaudharyG try this https://github.com/knadh/listmonk/issues/1169#issuecomment-1674475945
