### ISSUE TITLE
Transactional API email sending has no table in database.

### ISSUE THREAD

**Issue by ccfiel** [knadh/listmonk#907]
**Is your feature request related to a problem? Please describe.**
Transactional API email sending has no table in database.

**Describe the solution you'd like**
Calling transactional email should have a table in the database with field template id, subscriber id, viewed

And link_clicks table should also have a transactional id field

**Comment by knadh** [comment]
Hi @ccfiel. Tracking rough view counts on newsletters is understandable, but transactional emails that are generated per user when a particular transaction occurs (eg: user signup, order completion etc), unsure of the benefits.

**Comment by ccfiel** [comment]
We do transactional email in onboarding a user we monitor how effective our onboarding message.

**Comment by ccfiel** [comment]
@knadh we are using SendGrid they also have transactional email, and they track the events see image below
![ksnip_20220822-125435](https://user-images.githubusercontent.com/1788360/185842244-ee34dba2-1a0b-46f7-8600-a931264630ff.png)
.

**Comment by bamboowonder** [comment]
To add to this, and perhaps I should make a separate issue, is I imagine this is why the transactional email addresses are not scrubbed against blocklists.  I'm glad I tested that before realizing it.     One of the big valueadds of Listmonk transactional email is that it is integrated with blocklist/click tracking etc.  otherwise it would be easy enough to just use SES directly for transactional.
Side note, is SES now has a customer administered blocklist feature, so I can make sure unsubscribes/bounces are blocked at the SES level as a safety switch.

**Comment by knadh** [comment]
> To add to this, and perhaps I should make a separate issue, is I imagine this is why the transactional email addresses are not scrubbed against blocklists. I'm glad I tested that before realizing it. 

@bamboowonder, sorry, missed this. Transactional e-mails are validated against the domain blocklist. They're mapped to existing subscribers and it's not possible to create subscribers with blocklisted domains. Could you elaborate a bit on this?
