### ISSUE TITLE
Media API does not return width and height of image

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#938]
Looking at https://listmonk.app/docs/apis/media/#get-apimedia the api should return width and height. But they dont for me. I am using 2.2.0 right now.

Something like this would be expected:
```json
{
    "data": [
        {
            "id": 1,
            "uuid": "ec7b45ce-1408-4e5c-924e-965326a20287",
            "filename": "Media file",
            "width": 1080,
            "height": 1080,
            "created_at": "2020-04-08T22:43:45.080058+01:00",
            "thumb_uri": "/uploads/thumb_Media file",
            "uri": "/uploads/Media filE"
        }
    ]
}
```

**Comment by knadh** [comment]
Ah, this is an error in the documentation. The width and height of images are not stored in the database. Just fixed it.

**Comment by NicoHood** [comment]
Why? Dont you want to add this?

**Comment by knadh** [comment]
Since there are plans to add non-image media (arbitrary files), I was thinking `width` and `height` wouldn't be universally meaningful to all API responses. Non image files will come back with `null`s. But, thinking about it, it is useful to have this information. Maybe it can be in a `meta` field. eg: `meta: { width, height}`. Re-opening the issue.
