### ISSUE TITLE
Display number of subscribers in the "list" dropdown on the campaign creation page

### ISSUE THREAD

**Issue by Mattifyed** [knadh/listmonk#944]
Users may have similarly named lists, so would it be possible to show the size of a list along with list names on the campaign creation page? 

Additionally, Listmonk doesn't show empty lists in the dropdown. Perhaps showing it with the size (0) would be helpful.

**Comment by knadh** [comment]
> Users may have similarly named lists

I think it's best to name lists differently for multiple reasons!

> would it be possible to show the size of a list along with list names on the campaign creation page

This is not feasible, unfortunately. Counting subscribers is an extremely slow and expensive operation so much so that there are two separate queries for fetching lists; one with the subscriber count and one without. If you've noticed, on the lists page, the list names appear first and the counts appear several seconds later (for installations with large lists).


> Additionally, Listmonk doesn't show empty lists in the dropdown

This is not correct. listmonk shows all lists on the campaign's dropdown.

**Comment by Mattifyed** [comment]
Ah. I verified this behaviour. Looks like my dropdown was cached. Had to do a hard refresh for the new list to show up.
