### ISSUE TITLE
Reverse Proxy with NGINX

### ISSUE THREAD

**Issue by mbc3** [knadh/listmonk#949]
I am trying to set up a reverse proxy with nginx, so going to https://MY_URL/listmonk takes me to my listmonk app (running in a docker container).

I have SSL configured with Let's Encrypt, and can successfully see listmonk running on http://localhost:9000. When I visit https:/MY_URL/listmonk , the reverse proxy works - but the listmonk logo doesn't display. Inspecting the HTML makes me think that `/public/static/logo.svg` isn't being loaded, but I have no idea why. Is this an issue with permissions, or do I not have the proxy set up correctly? Or is it something else entirely?

Here's my relevant NGINX config block:

```
 location /listmonk/ {
     proxy_pass         http://localhost:9000/;
     proxy_set_header   Host            $http_host;
     proxy_set_header   X-Real-IP       $remote_addr;
     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;   
}
```

Please let me know if you need any other information.

**Comment by mbc3** [comment]
I should also add that I initially had trouble getting the reverse proxy working due to SELinux, as SELinux doesn't allow nginx to connect to other servers by default. This blog from nginx helped out - https://www.nginx.com/blog/using-nginx-plus-with-selinux/

This makes me think it might be another SELinux issue, but I'm stumped.

**Comment by knadh** [comment]
Please see this https://github.com/knadh/listmonk/issues/174. Unfortunately, it's very difficult to run listmonk (and any compiled Vue JS frontend with routing) on a subpath. It has to be a subdomain.

Navigating to `/admin` on your installation is broken, right?

> Inspecting the HTML makes me think that /public/static/logo.svg

What is the server returning here? 404?

**Comment by mbc3** [comment]
> What is the server returning here? 404?

Not a 404 - the images,css,etc weren't loading at all. So the page looked like
![listmonk_broken](https://user-images.githubusercontent.com/48695249/190874436-031bb819-2e00-4429-a82c-98892f3ce457.png)

But I took your advice to use a subdomain, and it worked perfectly. Thank you!

**Comment by alorimer** [comment]
I'm commenting on this issue because it would be really useful to be able to use reverse proxies on arbitrary URLs. Many apps I've come across allow you to set a base URL in the config file so you can run the reverse proxy on a subdirectory, not an entire subdomain. All the URLs in the HTML are then prepended appropriately and the API listens on the right addresses etc.

I had a look at how hard this would be but unfortunately I don't know anything about VueJS or how the frontend works. I successfully fixed the references in static templates with `{{ .RootURL }}` but that doesn't help for the admin interface.

@knadh, can you give me some pointers as to what I should change, or can someone look at actually implementing this? Ideally there would be an option in the config file for the "site URL", replacing `app_url` in the settings.
