### ISSUE TITLE
Make name field optional in POST /api/subscribers

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#967]
**Is your feature request related to a problem? Please describe.**

The `POST /api/subscribers` API call requires the `name` field, but this is not always available. Often, for brevity and ease of use, signup forms have only a single field for an email address.

(Related (and closed) issue #525 but that issue was not about the API.)

**Describe the solution you'd like**

Please make the `name` field _optional_ in the `POST /api/subscribers` API call.

**Comment by knadh** [comment]
Please see this https://github.com/knadh/listmonk/issues/594 for context on the decision to make name mandatory. In the API, if you don't have a name available, you can just pass the e-mail value as name.

**Comment by paulrudy** [comment]
Thanks for the quick reply, and I apologize for not finding that issue previously.

I'm not familiar with sprig functions referenced in the docs, but could those be used to adjust for the presence of an email addresses in the `{{ .Subscriber.Name }}` field when composing a template?

**Comment by knadh** [comment]
The issue is a matter of UX. With empty names, the subscriber list on the admin UI will look inconsistent. Most users who end up using the default template will see empty names, causing confusion.

**Comment by paulrudy** [comment]
Ok, I appreciate your explanation 🙌🏼

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/0d74619caca232983b428c9ac986b50b7cc19454 makes having to submit name via API and in the CSV file optional. If no name is provided, the name part of the e-mail is automatically extracted and assigned.

**Comment by ezuk** [comment]
This UX choice makes it so that interpolating names into emails ends up being either "Hi Charles" (if a name was provided) or "Hi charlie557z" (or whatever the email is) if a name was not provided.

The latter is exactly the opposite of personalization. The UX impact for the receiver of the mail is alienating. I would rather have an empty list in the admin panel any day.

For now, I've set up our forms to pass the string "there" when no name is provided, so this serves as a fallback ("Hi there" beats "Hi coolperson663").
